require('dotenv').config();
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

async function run() {
  // 1. All REDWINE artists in DB
  const r1 = await pool.query(
    `SELECT id, slug, artist_name, generated_by, created_at FROM users
     WHERE slug ILIKE '%redwine%' OR artist_name ILIKE '%REDWINE%'
     ORDER BY id`
  );
  console.log('=== ALL REDWINE/redwine artists in DB (' + r1.rows.length + ') ===');
  r1.rows.forEach(a => console.log('  ID', a.id, '|', a.slug, '|', a.artist_name, '| gen_by:', a.generated_by, '| created:', a.created_at?.toISOString().slice(0,10)));

  // 2. Check what tables exist that might relate to "My Artists"
  const tables = await pool.query(
    `SELECT table_name FROM information_schema.tables
     WHERE table_schema='public'
     ORDER BY table_name`
  );
  console.log('\n=== ALL public tables ===');
  tables.rows.forEach(t => process.stdout.write(t.table_name + '  '));
  console.log('');

  // 3. Artists generated by ALL users (to find who owns the redwine artists)
  const gen = await pool.query(
    `SELECT id, slug, artist_name, generated_by FROM users
     WHERE id BETWEEN 1380 AND 1410
     ORDER BY id`
  );
  console.log('\n=== Artists IDs 1380-1410 ===');
  gen.rows.forEach(a => console.log('  ID', a.id, '|', a.slug, '|', a.artist_name, '| gen_by:', a.generated_by));

  await pool.end();
}
run().catch(e => { console.error(e.message); pool.end(); });
