-- Agregar campos de AI a la tabla songs
ALTER TABLE songs ADD COLUMN IF NOT EXISTS mood TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS lyrics TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS artist_gender TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS generated_with_ai BOOLEAN DEFAULT FALSE;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS ai_provider TEXT;
