import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "../ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { useToast } from "../../hooks/use-toast";
import { Sparkles, Download, Loader, Palette, Trash2 } from "lucide-react";
import { apiRequest, queryClient } from "../../lib/queryClient";

interface AlbumGeneratorProps {
  artistName: string;
  biography: string;
  profileImage?: string;
  isAIGenerated?: boolean;
}

interface Song {
  title: string;
  lyrics: string;
  style: string;
  mood: string;
}

interface Album {
  artistName: string;
  albumTitle: string;
  releaseDate: string;
  genre: string;
  songs: Song[];
}

export function AlbumGenerator({ artistName, biography, profileImage, isAIGenerated }: AlbumGeneratorProps) {
  const { toast } = useToast();
  const [album, setAlbum] = useState<Album | null>(null);
  const [albumCover, setAlbumCover] = useState<string | null>(null);
  const [coverColor, setCoverColor] = useState<string>("#FF6B35");

  const generateAlbumMutation = useMutation({
    mutationFn: async () => {
      try {
        // Call backend to generate album using Gemini
        const response = await apiRequest('/api/generate-album', {
          method: 'POST',
          body: JSON.stringify({
            artistName,
            biography,
            profileImage
          }),
          headers: {
            'Content-Type': 'application/json',
          },
        });
        
        if (!response) {
          throw new Error('No response from server');
        }
        
        return response;
      } catch (error: any) {
        throw new Error(error.message || 'Failed to generate album');
      }
    },
    onSuccess: (data) => {
      if (data.albumData) {
        setAlbum({
          artistName,
          ...data.albumData
        });
      }
      if (data.coverColor) {
        setCoverColor(data.coverColor);
      }
      // Invalidate songs query to refresh music section
      const userId = (req.user as any)?.id || Number(artistName?.split('-')[0] || 0);
      queryClient.invalidateQueries({ queryKey: ['songs'] });
      queryClient.invalidateQueries({ queryKey: ['/api/songs'] });
      queryClient.invalidateQueries({ queryKey: ['/api/songs/user'] });
      toast({
        title: "✅ Éxito",
        description: "¡Álbum generado! Tus canciones aparecen en el perfil.",
      });
    },
    onError: (error: any) => {
      console.error('Album generation error:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to generate album",
        variant: "destructive",
      });
    },
  });

  const downloadAlbum = () => {
    if (!album) return;

    const albumText = `
═══════════════════════════════════════════════════════════════
${album.artistName} - ${album.albumTitle}
═══════════════════════════════════════════════════════════════
Genre: ${album.genre}
Release Date: ${album.releaseDate}
Total Tracks: ${album.songs.length}

═══════════════════════════════════════════════════════════════

${album.songs.map((song, index) => `
TRACK ${index + 1}: ${song.title}
Style: ${song.style}
Mood: ${song.mood}
───────────────────────────────────────────────────────────────

${song.lyrics}

═══════════════════════════════════════════════════════════════
`).join("\n")}

Generated by Boostify Music Platform
${new Date().toLocaleDateString()}
    `;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(albumText));
    element.setAttribute("download", `${album.artistName}_${album.albumTitle}_Album.txt`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const downloadCover = () => {
    // Generate a simple gradient cover since we're using backend
    const canvas = document.createElement('canvas');
    canvas.width = 1000;
    canvas.height = 1000;
    const ctx = canvas.getContext('2d');
    
    if (!ctx) return;
    
    // Create gradient background
    const gradient = ctx.createLinearGradient(0, 0, 1000, 1000);
    gradient.addColorStop(0, coverColor);
    gradient.addColorStop(1, adjustColor(coverColor, -30));
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 1000, 1000);
    
    // Add text
    ctx.fillStyle = 'white';
    ctx.font = 'bold 48px Arial';
    ctx.textAlign = 'center';
    ctx.fillText(album?.albumTitle || 'Album', 500, 450);
    ctx.font = '32px Arial';
    ctx.fillText(artistName, 500, 520);
    ctx.font = '24px Arial';
    ctx.fillStyle = 'rgba(255,255,255,0.8)';
    ctx.fillText(album?.genre || '', 500, 580);
    
    // Download
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${album?.artistName}_${album?.albumTitle}_Cover.png`;
      link.click();
      URL.revokeObjectURL(url);
    });
  };

  const adjustColor = (color: string, percent: number): string => {
    const num = parseInt(color.replace("#",""), 16);
    const amt = Math.round(2.55 * percent);
    const R = Math.min(255, Math.max(0, (num >> 16) + amt));
    const G = Math.min(255, Math.max(0, (num >> 8 & 0x00FF) + amt));
    const B = Math.min(255, Math.max(0, (num & 0x0000FF) + amt));
    return "#" + (0x1000000 + R*0x10000 + G*0x100 + B).toString(16).slice(1);
  };

  const downloadJSON = () => {
    if (!album) return;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(album, null, 2)));
    element.setAttribute("download", `${album.artistName}_${album.albumTitle}_Album.json`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const deleteSong = async (songId: number | null | undefined) => {
    if (!songId) return;
    
    try {
      await apiRequest(`/api/album-songs/${songId}`, {
        method: 'DELETE',
      });
      
      toast({
        title: "Success",
        description: "Song deleted successfully",
      });

      // Refresh album
      if (album) {
        setAlbum({
          ...album,
          songs: album.songs.filter((_, i) => 
            i >= album.songs.length - 1 || album.songs[i + 1]?.['songId'] !== songId
          ),
        });
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to delete song",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            AI Album Generator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Generate a complete 10-track album with AI-powered lyrics, melodies, and album artwork based on your artist profile.
          </p>
          
          <Button 
            onClick={() => generateAlbumMutation.mutate()}
            disabled={generateAlbumMutation.isPending}
            className="w-full"
            data-testid="button-generate-album"
          >
            {generateAlbumMutation.isPending ? (
              <>
                <Loader className="h-4 w-4 mr-2 animate-spin" />
                Generating Album...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4 mr-2" />
                Generate Album (10 Songs)
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {album && (
        <>
          <Card>
            <CardHeader>
              <CardTitle>{album.albumTitle}</CardTitle>
              <p className="text-sm text-muted-foreground">{album.genre} • {album.songs.length} Tracks • {album.releaseDate}</p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="w-full aspect-square rounded-lg overflow-hidden border-2" style={{ borderColor: coverColor }}>
                <div 
                  className="w-full h-full flex flex-col items-center justify-center text-white p-8"
                  style={{
                    background: `linear-gradient(135deg, ${coverColor} 0%, ${adjustColor(coverColor, -30)} 100%)`
                  }}
                >
                  {profileImage && (
                    <img src={profileImage} alt={artistName} className="w-32 h-32 rounded-full object-cover mb-4 border-4 border-white" />
                  )}
                  <h2 className="text-3xl font-bold text-center">{album.albumTitle}</h2>
                  <p className="text-xl mt-2">{artistName}</p>
                  <p className="text-sm mt-4 opacity-90">{album.genre}</p>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="font-bold">Tracklist ({album.songs.length} tracks):</h3>
                <div className="space-y-2 max-h-96 overflow-y-auto">
                  {album.songs.map((song: any, index: number) => (
                    <div key={index} className="text-sm p-3 bg-muted rounded border-l-2" style={{ borderLeftColor: coverColor }}>
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1">
                          <div className="font-medium">{index + 1}. {song.title}</div>
                          <div className="text-xs text-muted-foreground mt-1">{song.style} • {song.mood}</div>
                          {song.audioUrl && (
                            <audio controls className="w-full mt-2 h-6">
                              <source src={song.audioUrl} type="audio/mpeg" />
                            </audio>
                          )}
                        </div>
                        {song.songId && (
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => deleteSong(song.songId)}
                            className="text-destructive hover:text-destructive"
                            data-testid={`button-delete-generated-song-${song.songId}`}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-3 gap-2">
                <Button 
                  onClick={downloadAlbum}
                  variant="outline"
                  size="sm"
                  data-testid="button-download-lyrics"
                  className="flex-1"
                >
                  <Download className="h-4 w-4 mr-1" />
                  Lyrics (TXT)
                </Button>
                <Button 
                  onClick={downloadCover}
                  variant="outline"
                  size="sm"
                  data-testid="button-download-cover"
                  className="flex-1"
                >
                  <Palette className="h-4 w-4 mr-1" />
                  Cover (PNG)
                </Button>
                <Button 
                  onClick={downloadJSON}
                  variant="outline"
                  size="sm"
                  data-testid="button-download-json"
                  className="flex-1"
                >
                  <Download className="h-4 w-4 mr-1" />
                  JSON
                </Button>
              </div>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
