/**
 * Artist Business Plan Panel
 * 
 * Professional financial planning module with 6 tabs:
 * Overview, Financial Statements, Revenue Calculator, Budget Planner, Roadmap, Pitch Deck
 */

import { useState, useMemo, useCallback } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest } from "../../lib/queryClient";
import { queryClient } from "../../lib/queryClient";
import { useToast } from "../../hooks/use-toast";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Textarea } from "../ui/textarea";
import {
  Briefcase, DollarSign, TrendingUp, PieChart, Map, Presentation,
  ChevronDown, ChevronRight, Save, Sparkles, Plus, Trash2,
  Music, ShoppingBag, Mic, FileText, Users, Video, Target,
  ArrowUp, ArrowDown, Check, Loader2, BarChart3, Calculator,
  Calendar, Edit3, Download, CreditCard, Building2, Receipt,
  ExternalLink, Zap, Radio, Newspaper, Activity, Globe, Scan, Bot
} from "lucide-react";
import {
  ResponsiveContainer, BarChart, Bar, LineChart, Line, PieChart as RechartsPie, Pie, Cell,
  XAxis, YAxis, Tooltip, Legend, AreaChart, Area
} from "recharts";
import { PitchDeckSlides } from "./pitch-deck-slides";

interface ArtistBusinessPlanProps {
  artistId: string;
  pgId?: number;
  artistName: string;
  artistGenre?: string;
  artistBio?: string;
  isOwnProfile: boolean;
  isExpanded: boolean;
  onToggleExpand: () => void;
  colors: any;
  cardStyles: string;
  cardStyleInline: React.CSSProperties;
}

interface RevenueStreams {
  streaming: number;
  merchandise: number;
  liveShows: number;
  licensing: number;
  brandDeals: number;
  courses: number;
  crowdfunding: number;
  other: number;
}

interface MonthlyExpenses {
  studio: number;
  marketing: number;
  equipment: number;
  travel: number;
  contentCreation: number;
  team: number;
  distribution: number;
  other: number;
}

interface FinancialGoals {
  monthlyTarget: number;
  yearlyTarget: number;
  savingsTarget: number;
  investmentAsk: number;
}

interface Milestone {
  id?: string;
  title: string;
  date: string;
  category: string;
  status: 'planned' | 'in_progress' | 'completed';
  description?: string;
  completedAt?: string;
  autoGenerated?: boolean;
  linkedToEngine?: boolean;
  priority?: 'low' | 'medium' | 'high' | 'critical';
  profileMetric?: string;
  targetValue?: number;
  currentValue?: number;
  action?: { type: string; payload?: Record<string, any>; executedAt?: string; result?: string };
  newsPublished?: boolean;
}

interface ProfileSnapshot {
  artistId: number;
  artistName: string;
  totalSongs: number;
  totalMerch: number;
  totalTokens: number;
  socialLinksCount: number;
  hasSpotify: boolean;
  hasInstagram: boolean;
  hasTwitter: boolean;
  hasYoutube: boolean;
  hasTikTok: boolean;
  hasFacebook: boolean;
  engineEnabled: boolean;
  engineMode: string;
  vaultTotal: number;
  profileCompleteness: number;
  hasBiography: boolean;
  hasBusinessPlan: boolean;
  hasPitchDeck: boolean;
  scannedAt: string;
}

interface BusinessPlan {
  id: number;
  artistId: number;
  businessName: string | null;
  executiveSummary: string | null;
  missionStatement: string | null;
  revenueStreams: RevenueStreams | null;
  monthlyExpenses: MonthlyExpenses | null;
  financialGoals: FinancialGoals | null;
  milestones: Milestone[] | null;
  pitchDeckData: any;
  projections: any;
  budgetAllocation: Record<string, number> | null;
}

type TabId = 'overview' | 'financials' | 'calculator' | 'budget' | 'roadmap' | 'pitch';

const REVENUE_LABELS: Record<keyof RevenueStreams, { label: string; icon: any; color: string }> = {
  streaming: { label: 'Streaming', icon: Music, color: '#22c55e' },
  merchandise: { label: 'Merchandise', icon: ShoppingBag, color: '#f97316' },
  liveShows: { label: 'Live Shows', icon: Mic, color: '#8b5cf6' },
  licensing: { label: 'Licensing', icon: FileText, color: '#06b6d4' },
  brandDeals: { label: 'Brand Deals', icon: Users, color: '#ec4899' },
  courses: { label: 'Courses', icon: Video, color: '#eab308' },
  crowdfunding: { label: 'Crowdfunding', icon: Target, color: '#14b8a6' },
  other: { label: 'Other', icon: DollarSign, color: '#64748b' },
};

const EXPENSE_LABELS: Record<keyof MonthlyExpenses, { label: string; color: string }> = {
  studio: { label: 'Studio Time', color: '#ef4444' },
  marketing: { label: 'Marketing', color: '#f97316' },
  equipment: { label: 'Equipment', color: '#eab308' },
  travel: { label: 'Travel / Touring', color: '#22c55e' },
  contentCreation: { label: 'Content Creation', color: '#06b6d4' },
  team: { label: 'Team / Payroll', color: '#8b5cf6' },
  distribution: { label: 'Distribution', color: '#ec4899' },
  other: { label: 'Other', color: '#64748b' },
};

const BUDGET_COLORS = ['#22c55e', '#f97316', '#8b5cf6', '#06b6d4', '#ec4899', '#eab308', '#14b8a6', '#64748b'];

const CATEGORY_ICONS: Record<string, { icon: any; color: string; label: string }> = {
  release:       { icon: Music,       color: '#a855f7', label: 'Release' },
  tour:          { icon: Mic,         color: '#f97316', label: 'Tour' },
  marketing:     { icon: Radio,       color: '#ec4899', label: 'Marketing' },
  financial:     { icon: DollarSign,  color: '#22c55e', label: 'Financial' },
  branding:      { icon: Sparkles,    color: '#06b6d4', label: 'Branding' },
  collaboration: { icon: Users,       color: '#3b82f6', label: 'Collab' },
  engine:        { icon: Zap,         color: '#eab308', label: 'Engine' },
  growth:        { icon: TrendingUp,  color: '#14b8a6', label: 'Growth' },
  music:         { icon: Music,       color: '#8b5cf6', label: 'Music' },
  revenue:       { icon: BarChart3,   color: '#22c55e', label: 'Revenue' },
};
const getCategoryMeta = (cat?: string) =>
  CATEGORY_ICONS[cat || ''] || { icon: Target, color: '#94a3b8', label: cat || 'Other' };

export function ArtistBusinessPlan({
  artistId,
  pgId,
  artistName,
  artistGenre,
  artistBio,
  isOwnProfile,
  isExpanded,
  onToggleExpand,
  colors,
  cardStyles,
  cardStyleInline,
}: ArtistBusinessPlanProps) {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<TabId>('overview');
  const numericId = pgId || parseInt(artistId) || 0;

  // ─── Fetch business plan ───
  const { data: planData, isLoading } = useQuery({
    queryKey: ['business-plan', numericId],
    queryFn: async () => {
      const res = await apiRequest('GET', `/api/business-plan/${numericId}`);
      const data = await res.json();
      return data.plan as BusinessPlan | null;
    },
    enabled: numericId > 0,
  });

  // ─── Local state for editing ───
  const [businessName, setBusinessName] = useState('');
  const [missionStatement, setMissionStatement] = useState('');
  const [revenue, setRevenue] = useState<RevenueStreams>({
    streaming: 0, merchandise: 0, liveShows: 0, licensing: 0,
    brandDeals: 0, courses: 0, crowdfunding: 0, other: 0,
  });
  const [expenses, setExpenses] = useState<MonthlyExpenses>({
    studio: 0, marketing: 0, equipment: 0, travel: 0,
    contentCreation: 0, team: 0, distribution: 0, other: 0,
  });
  const [goals, setGoals] = useState<FinancialGoals>({
    monthlyTarget: 5000, yearlyTarget: 60000, savingsTarget: 10000, investmentAsk: 0,
  });
  const [milestones, setMilestones] = useState<Milestone[]>([]);
  const [budgetAlloc, setBudgetAlloc] = useState<Record<string, number>>({
    marketing: 35, production: 25, equipment: 15, touring: 15, content: 10,
  });
  const [initialized, setInitialized] = useState(false);
  const [autoPopulating, setAutoPopulating] = useState(false);
  const [lastAdapt, setLastAdapt] = useState<string | null>(null);

  // ─── Auto-Populate mutation (full AI + data-driven plan gen) ───
  const autoPopulateMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}/auto-populate`);
      return res.json();
    },
    onSuccess: (data: any) => {
      if (data.plan) {
        syncLocalState(data.plan);
        toast({
          title: '✨ Business Plan Auto-Generated',
          description: `${data.fieldsUpdated?.length || 0} fields populated from your profile`,
        });
      }
      setAutoPopulating(false);
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
      queryClient.invalidateQueries({ queryKey: ['business-plan-dashboard', numericId] });
    },
    onError: () => {
      setAutoPopulating(false);
      toast({ title: '❌ Auto-populate failed', variant: 'destructive' });
    },
  });

  // ─── Re-adapt mutation (light financial recalculation, no AI) ───
  const readaptMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}/readapt`);
      return res.json();
    },
    onSuccess: (data: any) => {
      if (data.plan) {
        syncLocalState(data.plan);
        setLastAdapt(new Date().toLocaleTimeString());
      }
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
    },
  });

  // ─── Helper: sync plan data into local state ───
  const syncLocalState = useCallback((plan: any) => {
    if (plan.businessName) setBusinessName(plan.businessName);
    if (plan.missionStatement) setMissionStatement(plan.missionStatement);
    if (plan.revenueStreams) setRevenue(plan.revenueStreams);
    if (plan.monthlyExpenses) setExpenses(plan.monthlyExpenses);
    if (plan.financialGoals) setGoals(plan.financialGoals);
    if (plan.milestones) setMilestones(plan.milestones);
    if (plan.budgetAllocation) setBudgetAlloc(plan.budgetAllocation);
  }, []);

  // Sync from DB on first load — if plan is null/empty, auto-populate
  if (planData !== undefined && !initialized) {
    if (planData) {
      syncLocalState(planData);
      setInitialized(true);
      // Light re-adapt on every load (non-blocking)
      if (isOwnProfile && numericId > 0) {
        setTimeout(() => readaptMutation.mutate(), 500);
      }
    } else if (isOwnProfile && numericId > 0 && !autoPopulating) {
      // No plan exists — auto-populate everything
      setAutoPopulating(true);
      setInitialized(true);
      autoPopulateMutation.mutate();
    } else {
      setInitialized(true);
    }
  }

  // ─── Computed values ───
  const totalRevenue = useMemo(() => Object.values(revenue).reduce((a, b) => a + b, 0), [revenue]);
  const totalExpenses = useMemo(() => Object.values(expenses).reduce((a, b) => a + b, 0), [expenses]);
  const monthlyProfit = totalRevenue - totalExpenses;
  const annualRevenue = totalRevenue * 12;
  const annualProfit = monthlyProfit * 12;
  const profitMargin = totalRevenue > 0 ? (monthlyProfit / totalRevenue) * 100 : 0;

  // ─── 12-month projections ───
  const projections12 = useMemo(() => {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const growthRate = 0.05; // 5% monthly growth
    return months.map((m, i) => {
      const factor = Math.pow(1 + growthRate, i);
      const rev = Math.round(totalRevenue * factor);
      const exp = Math.round(totalExpenses * (1 + i * 0.01));
      return { month: m, revenue: rev, expenses: exp, profit: rev - exp };
    });
  }, [totalRevenue, totalExpenses]);

  // ─── Revenue pie data ───
  const revenuePieData = useMemo(() =>
    Object.entries(revenue)
      .filter(([, v]) => v > 0)
      .map(([k, v]) => ({
        name: REVENUE_LABELS[k as keyof RevenueStreams]?.label || k,
        value: v,
        color: REVENUE_LABELS[k as keyof RevenueStreams]?.color || '#666',
      })),
    [revenue]
  );

  // ─── Budget pie data ───
  const budgetPieData = useMemo(() =>
    Object.entries(budgetAlloc)
      .filter(([, v]) => v > 0)
      .map(([k, v], i) => ({
        name: k.charAt(0).toUpperCase() + k.slice(1),
        value: v,
        color: BUDGET_COLORS[i % BUDGET_COLORS.length],
      })),
    [budgetAlloc]
  );

  // ─── Save mutation ───
  const saveMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}`, {
        businessName,
        missionStatement,
        revenueStreams: revenue,
        monthlyExpenses: expenses,
        financialGoals: goals,
        milestones,
        budgetAllocation: budgetAlloc,
        projections: projections12,
      });
      return res.json();
    },
    onSuccess: () => {
      toast({ title: '✅ Business Plan Saved' });
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
    },
    onError: () => toast({ title: '❌ Failed to save', variant: 'destructive' }),
  });

  // ─── AI Summary mutation ───
  const summaryMutation = useMutation({
    mutationFn: async () => {
      return await apiRequest('POST', `/api/business-plan/${numericId}/generate-summary`, {
        artistName, genre: artistGenre, revenueStreams: revenue,
        monthlyExpenses: expenses, financialGoals: goals, milestones,
      });
    },
    onSuccess: (data: any) => {
      const isFallback = data?.aiSource === 'fallback';
      toast({
        title: isFallback ? '📝 Summary Generated (template)' : '✨ Executive Summary Generated',
        description: isFallback ? 'AI is unavailable — used a deterministic template based on your data.' : undefined,
      });
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
    },
    onError: (err: any) => {
      toast({ title: '❌ Failed to generate summary', description: String(err?.message || '').slice(0, 200), variant: 'destructive' });
    },
  });

  // ─── AI Pitch mutation ───
  const pitchMutation = useMutation({
    mutationFn: async () => {
      return await apiRequest('POST', `/api/business-plan/${numericId}/generate-pitch`, {
        artistName, genre: artistGenre, biography: artistBio,
        revenueStreams: revenue, monthlyExpenses: expenses,
        financialGoals: goals, milestones,
      });
    },
    onSuccess: (data: any) => {
      const isFallback = data?.aiSource === 'fallback';
      toast({
        title: isFallback ? '🎤 Pitch Deck Generated (template)' : '🎤 Pitch Deck Generated',
        description: isFallback ? 'AI is unavailable — built deterministic slides from your catalog & financials.' : undefined,
      });
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
    },
    onError: (err: any) => {
      toast({ title: '❌ Failed to generate pitch', description: String(err?.message || '').slice(0, 200), variant: 'destructive' });
    },
  });

  // ─── Sync Engine mutation ───
  const syncEngineMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}/sync-engine`);
      return res.json();
    },
    onSuccess: (data: any) => {
      toast({ title: '⚡ Economic Engine synced' });
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
      queryClient.invalidateQueries({ queryKey: ['business-plan-dashboard', numericId] });
    },
    onError: () => toast({ title: '❌ Failed to sync engine', variant: 'destructive' }),
  });

  // ─── Update Roadmap mutation ───
  const updateRoadmapMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}/update-roadmap`);
      return res.json();
    },
    onSuccess: (data: any) => {
      if (data.updated?.length > 0) {
        toast({ title: `🎯 ${data.updated.length} milestone(s) updated` });
      } else {
        toast({ title: '✅ Roadmap is up to date' });
      }
      if (data.milestones) setMilestones(data.milestones);
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
    },
    onError: () => toast({ title: '❌ Failed to update roadmap', variant: 'destructive' }),
  });

  // ─── Full Roadmap Scan — profile → milestones → actions → news ───
  const [scanResult, setScanResult] = useState<any>(null);
  const [aiAdvice, setAiAdvice] = useState<string | null>(null);

  const roadmapScanMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}/roadmap-scan`);
      return res.json();
    },
    onSuccess: (data: any) => {
      setScanResult(data);
      if (data.milestones) setMilestones(data.milestones);
      const created = data.milestonesCreated?.length || 0;
      const updated = data.milestonesUpdated?.length || 0;
      const news = data.newsGenerated?.length || 0;
      toast({
        title: '🔍 Roadmap Scan Complete',
        description: `${created} new milestones, ${updated} updated, ${news} news published`,
      });
      queryClient.invalidateQueries({ queryKey: ['business-plan', numericId] });
      queryClient.invalidateQueries({ queryKey: ['business-plan-dashboard', numericId] });
      queryClient.invalidateQueries({ queryKey: ['profile-snapshot', numericId] });
    },
    onError: () => toast({ title: '❌ Scan failed', variant: 'destructive' }),
  });

  // ─── Profile Snapshot (all tabs — powers real-time adaptation) ───
  const { data: snapshotData } = useQuery<{ success: boolean; snapshot: ProfileSnapshot }>({
    queryKey: ['profile-snapshot', numericId],
    queryFn: async () => {
      const res = await apiRequest('GET', `/api/business-plan/${numericId}/profile-snapshot`);
      return res.json();
    },
    enabled: numericId > 0,
    refetchInterval: 60000, // refresh every minute
  });

  // ─── AI Roadmap Advice ───
  const adviceMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/business-plan/${numericId}/roadmap-advice`);
      return res.json();
    },
    onSuccess: (data: any) => {
      setAiAdvice(data.advice || null);
    },
    onError: () => toast({ title: '❌ Failed to get advice', variant: 'destructive' }),
  });

  // ─── Combined dashboard data ───
  const { data: dashboardData } = useQuery({
    queryKey: ['business-plan-dashboard', numericId],
    queryFn: async () => {
      const res = await apiRequest('GET', `/api/business-plan/${numericId}/dashboard`);
      return res.json();
    },
    enabled: numericId > 0,
  });

  // ─── Milestone helpers ───
  const addMilestone = useCallback(() => {
    setMilestones(prev => [...prev, {
      title: '', date: new Date().toISOString().split('T')[0],
      category: 'release', status: 'planned',
    }]);
  }, []);

  const updateMilestone = useCallback((index: number, field: string, value: any) => {
    setMilestones(prev => prev.map((m, i) => i === index ? { ...m, [field]: value } : m));
  }, []);

  const removeMilestone = useCallback((index: number) => {
    setMilestones(prev => prev.filter((_, i) => i !== index));
  }, []);

  // ─── Tab definitions ───
  const tabs: { id: TabId; label: string; icon: any }[] = [
    { id: 'overview', label: 'Overview', icon: Briefcase },
    { id: 'financials', label: 'Financials', icon: DollarSign },
    { id: 'calculator', label: 'Calculator', icon: Calculator },
    { id: 'budget', label: 'Budget', icon: PieChart },
    { id: 'roadmap', label: 'Roadmap', icon: Map },
    { id: 'pitch', label: 'Pitch Deck', icon: Presentation },
  ];

  const fmt = (n: number) => n >= 1000 ? `$${(n / 1000).toFixed(1)}K` : `$${n}`;
  const fmtFull = (n: number) => `$${n.toLocaleString()}`;

  return (
    <div className={cardStyles} style={cardStyleInline}>
      {/* Header */}
      <button
        onClick={onToggleExpand}
        className="w-full text-left mb-4 flex items-center gap-2 hover:opacity-80 transition-opacity"
      >
        <div className="text-base font-semibold transition-colors duration-500 flex items-center gap-2 flex-1" style={{ color: colors.hexAccent }}>
          {isExpanded ? <ChevronDown className="h-5 w-5" /> : <ChevronRight className="h-5 w-5" />}
          <Briefcase className="h-5 w-5" />
          📊 Business Plan
        </div>
        <div className="flex items-center gap-2">
          {snapshotData?.snapshot && (
            <span className="flex items-center gap-1 text-[10px] text-green-400">
              <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
              Live
            </span>
          )}
          {totalRevenue > 0 && (
            <span className="text-xs text-white/50">{fmtFull(totalRevenue)}/mo</span>
          )}
        </div>
      </button>

      {isExpanded && (
        <div className="space-y-4">
          {/* Tab Navigation */}
          <div className="flex flex-wrap gap-1 p-1 rounded-lg bg-black/20">
            {tabs.map(tab => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                    activeTab === tab.id
                      ? 'bg-gradient-to-r text-white shadow-lg'
                      : 'text-white/60 hover:text-white/80 hover:bg-white/5'
                  }`}
                  style={activeTab === tab.id ? { background: `linear-gradient(135deg, ${colors.hexAccent}90, ${colors.hexAccent}60)` } : {}}
                >
                  <Icon className="h-3.5 w-3.5" />
                  <span className="hidden sm:inline">{tab.label}</span>
                </button>
              );
            })}
          </div>

          {/* External Services */}
          <div className="flex flex-wrap gap-2">
            <a
              href="https://omniastartupslab.com/#credit"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-emerald-500/15 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/25 hover:border-emerald-500/40 transition-all"
            >
              <CreditCard className="h-3.5 w-3.5" />
              Credit
              <ExternalLink className="h-3 w-3 opacity-50" />
            </a>
            <a
              href="https://omniastartupslab.com/#business-structure"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-blue-500/15 text-blue-400 border border-blue-500/20 hover:bg-blue-500/25 hover:border-blue-500/40 transition-all"
            >
              <Building2 className="h-3.5 w-3.5" />
              Business Structure
              <ExternalLink className="h-3 w-3 opacity-50" />
            </a>
            <a
              href="https://www.omnia.tax"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-purple-500/15 text-purple-400 border border-purple-500/20 hover:bg-purple-500/25 hover:border-purple-500/40 transition-all"
            >
              <Receipt className="h-3.5 w-3.5" />
              Taxes
              <ExternalLink className="h-3 w-3 opacity-50" />
            </a>
          </div>

          {/* Auto-populating indicator */}
          {autoPopulating && (
            <div className="rounded-xl p-4 text-center border" style={{ background: `${colors.hexAccent}10`, borderColor: `${colors.hexAccent}30` }}>
              <Loader2 className="h-6 w-6 animate-spin mx-auto mb-2" style={{ color: colors.hexAccent }} />
              <p className="text-xs text-white/70">Analyzing your profile and generating your business plan...</p>
              <p className="text-[10px] text-white/40 mt-1">Connecting to songs, merch, tokens, vault, and social data</p>
            </div>
          )}

          {/* Save & Adapt Buttons */}
          {isOwnProfile && (
            <div className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                {lastAdapt && (
                  <span className="text-[10px] text-white/30">Adapted at {lastAdapt}</span>
                )}
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => readaptMutation.mutate()}
                  disabled={readaptMutation.isPending}
                  className="text-[10px] h-6"
                  style={{ color: colors.hexAccent }}
                >
                  {readaptMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <><Zap className="h-3 w-3 mr-0.5" /> Re-adapt</>}
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => { setAutoPopulating(true); autoPopulateMutation.mutate(); }}
                  disabled={autoPopulateMutation.isPending}
                  className="text-[10px] h-6"
                  style={{ color: colors.hexAccent }}
                >
                  {autoPopulateMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <><Sparkles className="h-3 w-3 mr-0.5" /> Full Rebuild</>}
                </Button>
              </div>
              <Button
                size="sm"
                onClick={() => saveMutation.mutate()}
                disabled={saveMutation.isPending}
                className="text-xs"
                style={{ background: colors.hexAccent }}
              >
                {saveMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Save className="h-3 w-3 mr-1" />}
                Save Plan
              </Button>
            </div>
          )}

          {isLoading && (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-6 w-6 animate-spin text-white/40" />
            </div>
          )}

          {!isLoading && (
            <>
              {/* ─── OVERVIEW TAB ─── */}
              {activeTab === 'overview' && (
                <div className="space-y-4">
                  {/* KPI Cards */}
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                    {[
                      { label: 'Monthly Revenue', value: fmtFull(totalRevenue), color: '#22c55e', icon: TrendingUp },
                      { label: 'Monthly Expenses', value: fmtFull(totalExpenses), color: '#ef4444', icon: ArrowDown },
                      { label: 'Monthly Profit', value: fmtFull(monthlyProfit), color: monthlyProfit >= 0 ? '#22c55e' : '#ef4444', icon: monthlyProfit >= 0 ? ArrowUp : ArrowDown },
                      { label: 'Profit Margin', value: `${profitMargin.toFixed(1)}%`, color: profitMargin >= 0 ? '#22c55e' : '#ef4444', icon: BarChart3 },
                    ].map((kpi, i) => {
                      const KIcon = kpi.icon;
                      return (
                        <div key={i} className="rounded-xl p-3 bg-black/20 border border-white/5">
                          <div className="flex items-center gap-1.5 mb-1">
                            <KIcon className="h-3.5 w-3.5" style={{ color: kpi.color }} />
                            <span className="text-[10px] text-white/50 uppercase tracking-wider">{kpi.label}</span>
                          </div>
                          <div className="text-lg font-bold" style={{ color: kpi.color }}>{kpi.value}</div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Economic Engine Connection Card */}
                  {dashboardData && (
                    <div className="rounded-xl p-4 border" style={{ background: `linear-gradient(135deg, ${colors.hexAccent}08, transparent)`, borderColor: `${colors.hexAccent}20` }}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className="text-sm font-semibold text-white/90 flex items-center gap-1.5">
                          ⚡ Economic Engine L3
                        </h4>
                        <div className="flex items-center gap-1.5">
                          <div className={`w-2 h-2 rounded-full ${dashboardData.isLinked ? 'bg-green-400 animate-pulse' : 'bg-gray-500'}`} />
                          <span className="text-[10px] text-white/60">{dashboardData.isLinked ? 'Connected' : 'Not Connected'}</span>
                        </div>
                      </div>
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                        <div className="rounded-lg p-2 bg-black/30 text-center">
                          <div className="text-xs text-white/50">Mode</div>
                          <div className="text-sm font-bold capitalize" style={{ color: colors.hexAccent }}>{dashboardData.engineMode || '—'}</div>
                        </div>
                        <div className="rounded-lg p-2 bg-black/30 text-center">
                          <div className="text-xs text-white/50">Treasury</div>
                          <div className="text-sm font-bold text-green-400">{fmt(dashboardData.totalVault || 0)}</div>
                        </div>
                        <div className="rounded-lg p-2 bg-black/30 text-center">
                          <div className="text-xs text-white/50">Milestones</div>
                          <div className="text-sm font-bold text-white">{dashboardData.milestones?.completed || 0}/{dashboardData.milestones?.total || 0}</div>
                        </div>
                        <div className="rounded-lg p-2 bg-black/30 text-center">
                          <div className="text-xs text-white/50">In Progress</div>
                          <div className="text-sm font-bold text-yellow-400">{dashboardData.milestones?.inProgress || 0}</div>
                        </div>
                      </div>
                      {isOwnProfile && !dashboardData.isLinked && (
                        <Button
                          size="sm"
                          onClick={() => syncEngineMutation.mutate()}
                          disabled={syncEngineMutation.isPending}
                          className="w-full mt-3 text-xs"
                          style={{ background: `linear-gradient(135deg, ${colors.hexPrimary}, ${colors.hexAccent})`, color: 'white' }}
                        >
                          {syncEngineMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : '⚡'} Connect Economic Engine
                        </Button>
                      )}
                    </div>
                  )}

                  {/* Business Info */}
                  {isOwnProfile && (
                    <div className="grid gap-3">
                      <div>
                        <label className="text-xs text-white/50 mb-1 block">Business Name</label>
                        <Input
                          value={businessName}
                          onChange={e => setBusinessName(e.target.value)}
                          placeholder={`${artistName} Music LLC`}
                          className="bg-black/20 border-white/10 text-white text-sm"
                        />
                      </div>
                      <div>
                        <label className="text-xs text-white/50 mb-1 block">Mission Statement</label>
                        <Textarea
                          value={missionStatement}
                          onChange={e => setMissionStatement(e.target.value)}
                          placeholder="Our mission is to create authentic music that connects with audiences worldwide..."
                          className="bg-black/20 border-white/10 text-white text-sm min-h-[60px]"
                        />
                      </div>
                    </div>
                  )}

                  {/* Executive Summary */}
                  <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="text-sm font-semibold text-white/90 flex items-center gap-1.5">
                        <FileText className="h-4 w-4" style={{ color: colors.hexAccent }} />
                        Executive Summary
                      </h4>
                      {isOwnProfile && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => summaryMutation.mutate()}
                          disabled={summaryMutation.isPending}
                          className="text-xs h-7"
                        >
                          {summaryMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Sparkles className="h-3 w-3 mr-1" />}
                          Generate with AI
                        </Button>
                      )}
                    </div>
                    {planData?.executiveSummary ? (
                      <p className="text-xs text-white/70 leading-relaxed whitespace-pre-line">
                        {planData.executiveSummary}
                      </p>
                    ) : (
                      <p className="text-xs text-white/40 italic">
                        No executive summary yet. Fill in your financials and click "Generate with AI" to create one.
                      </p>
                    )}
                  </div>

                  {/* Revenue Projections Chart */}
                  {totalRevenue > 0 && (
                    <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                      <h4 className="text-sm font-semibold text-white/90 mb-3">12-Month Revenue Projection</h4>
                      <ResponsiveContainer width="100%" height={200}>
                        <AreaChart data={projections12}>
                          <XAxis dataKey="month" tick={{ fontSize: 10, fill: '#ffffff60' }} />
                          <YAxis tick={{ fontSize: 10, fill: '#ffffff60' }} tickFormatter={v => fmt(v)} />
                          <Tooltip
                            contentStyle={{ background: '#111', border: '1px solid #333', borderRadius: 8, fontSize: 11 }}
                            formatter={(v: number) => [fmtFull(v), '']}
                          />
                          <Area type="monotone" dataKey="revenue" stroke="#22c55e" fill="#22c55e20" strokeWidth={2} />
                          <Area type="monotone" dataKey="expenses" stroke="#ef4444" fill="#ef444420" strokeWidth={2} />
                          <Area type="monotone" dataKey="profit" stroke={colors.hexAccent} fill={`${colors.hexAccent}20`} strokeWidth={2} />
                          <Legend wrapperStyle={{ fontSize: 10 }} />
                        </AreaChart>
                      </ResponsiveContainer>
                    </div>
                  )}
                </div>
              )}

              {/* ─── FINANCIALS TAB ─── */}
              {activeTab === 'financials' && (
                <div className="space-y-4">
                  {/* Income Statement */}
                  <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                    <h4 className="text-sm font-semibold text-white/90 mb-3 flex items-center gap-1.5">
                      <DollarSign className="h-4 w-4" style={{ color: colors.hexAccent }} />
                      Income Statement (Monthly)
                    </h4>
                    <div className="space-y-2">
                      <div className="text-xs font-semibold text-white/50 uppercase tracking-wider">Revenue</div>
                      {Object.entries(REVENUE_LABELS).map(([key, { label, color }]) => (
                        <div key={key} className="flex items-center justify-between py-1 border-b border-white/5">
                          <span className="text-xs text-white/70 flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full" style={{ background: color }} />
                            {label}
                          </span>
                          <span className="text-xs font-mono text-white/90">{fmtFull(revenue[key as keyof RevenueStreams])}</span>
                        </div>
                      ))}
                      <div className="flex items-center justify-between py-1.5 border-t border-white/20 font-semibold">
                        <span className="text-xs text-green-400">Total Revenue</span>
                        <span className="text-sm font-mono text-green-400">{fmtFull(totalRevenue)}</span>
                      </div>

                      <div className="text-xs font-semibold text-white/50 uppercase tracking-wider mt-3">Expenses</div>
                      {Object.entries(EXPENSE_LABELS).map(([key, { label, color }]) => (
                        <div key={key} className="flex items-center justify-between py-1 border-b border-white/5">
                          <span className="text-xs text-white/70 flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full" style={{ background: color }} />
                            {label}
                          </span>
                          <span className="text-xs font-mono text-white/90">{fmtFull(expenses[key as keyof MonthlyExpenses])}</span>
                        </div>
                      ))}
                      <div className="flex items-center justify-between py-1.5 border-t border-white/20 font-semibold">
                        <span className="text-xs text-red-400">Total Expenses</span>
                        <span className="text-sm font-mono text-red-400">{fmtFull(totalExpenses)}</span>
                      </div>

                      <div className="flex items-center justify-between py-2 border-t-2 border-white/20 mt-2">
                        <span className="text-sm font-bold" style={{ color: monthlyProfit >= 0 ? '#22c55e' : '#ef4444' }}>
                          Net Profit
                        </span>
                        <span className="text-lg font-bold font-mono" style={{ color: monthlyProfit >= 0 ? '#22c55e' : '#ef4444' }}>
                          {fmtFull(monthlyProfit)}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Annual Summary */}
                  <div className="grid grid-cols-3 gap-3">
                    <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                      <div className="text-[10px] text-white/50 uppercase">Annual Revenue</div>
                      <div className="text-lg font-bold text-green-400">{fmt(annualRevenue)}</div>
                    </div>
                    <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                      <div className="text-[10px] text-white/50 uppercase">Annual Profit</div>
                      <div className="text-lg font-bold" style={{ color: annualProfit >= 0 ? '#22c55e' : '#ef4444' }}>{fmt(annualProfit)}</div>
                    </div>
                    <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                      <div className="text-[10px] text-white/50 uppercase">Margin</div>
                      <div className="text-lg font-bold" style={{ color: profitMargin >= 0 ? '#22c55e' : '#ef4444' }}>{profitMargin.toFixed(1)}%</div>
                    </div>
                  </div>

                  {/* Revenue Pie */}
                  {revenuePieData.length > 0 && (
                    <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                      <h4 className="text-sm font-semibold text-white/90 mb-3">Revenue Distribution</h4>
                      <ResponsiveContainer width="100%" height={200}>
                        <RechartsPie>
                          <Pie data={revenuePieData} cx="50%" cy="50%" innerRadius={50} outerRadius={80} dataKey="value" label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}>
                            {revenuePieData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
                          </Pie>
                          <Tooltip contentStyle={{ background: '#111', border: '1px solid #333', borderRadius: 8, fontSize: 11 }} />
                        </RechartsPie>
                      </ResponsiveContainer>
                    </div>
                  )}
                </div>
              )}

              {/* ─── CALCULATOR TAB ─── */}
              {activeTab === 'calculator' && (
                <div className="space-y-4">
                  <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                    <h4 className="text-sm font-semibold text-white/90 mb-3 flex items-center gap-1.5">
                      <Calculator className="h-4 w-4" style={{ color: colors.hexAccent }} />
                      Revenue Calculator
                    </h4>
                    <p className="text-[10px] text-white/40 mb-4">Adjust your income streams to project monthly and annual earnings</p>

                    <div className="space-y-3">
                      {Object.entries(REVENUE_LABELS).map(([key, { label, icon: Icon, color }]) => (
                        <div key={key}>
                          <div className="flex items-center justify-between mb-1">
                            <span className="text-xs text-white/70 flex items-center gap-1.5">
                              <Icon className="h-3.5 w-3.5" style={{ color }} />
                              {label}
                            </span>
                            <span className="text-xs font-mono font-semibold" style={{ color }}>
                              {fmtFull(revenue[key as keyof RevenueStreams])}
                            </span>
                          </div>
                          <input
                            type="range"
                            min={0}
                            max={key === 'liveShows' ? 50000 : key === 'brandDeals' ? 25000 : 10000}
                            step={key === 'liveShows' ? 500 : 100}
                            value={revenue[key as keyof RevenueStreams]}
                            onChange={e => setRevenue(prev => ({ ...prev, [key]: parseInt(e.target.value) }))}
                            className="w-full h-1.5 rounded-full appearance-none cursor-pointer"
                            style={{
                              background: `linear-gradient(to right, ${color} 0%, ${color} ${(revenue[key as keyof RevenueStreams] / (key === 'liveShows' ? 50000 : key === 'brandDeals' ? 25000 : 10000)) * 100}%, #333 ${(revenue[key as keyof RevenueStreams] / (key === 'liveShows' ? 50000 : key === 'brandDeals' ? 25000 : 10000)) * 100}%, #333 100%)`,
                            }}
                          />
                        </div>
                      ))}
                    </div>

                    {/* Expense sliders */}
                    <div className="mt-6 pt-4 border-t border-white/10">
                      <h4 className="text-sm font-semibold text-white/90 mb-3 flex items-center gap-1.5">
                        <ArrowDown className="h-4 w-4 text-red-400" />
                        Monthly Expenses
                      </h4>
                      <div className="space-y-3">
                        {Object.entries(EXPENSE_LABELS).map(([key, { label, color }]) => (
                          <div key={key}>
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-xs text-white/70">{label}</span>
                              <span className="text-xs font-mono font-semibold" style={{ color }}>
                                {fmtFull(expenses[key as keyof MonthlyExpenses])}
                              </span>
                            </div>
                            <input
                              type="range"
                              min={0}
                              max={key === 'team' ? 15000 : 5000}
                              step={50}
                              value={expenses[key as keyof MonthlyExpenses]}
                              onChange={e => setExpenses(prev => ({ ...prev, [key]: parseInt(e.target.value) }))}
                              className="w-full h-1.5 rounded-full appearance-none cursor-pointer"
                              style={{
                                background: `linear-gradient(to right, ${color} 0%, ${color} ${(expenses[key as keyof MonthlyExpenses] / (key === 'team' ? 15000 : 5000)) * 100}%, #333 ${(expenses[key as keyof MonthlyExpenses] / (key === 'team' ? 15000 : 5000)) * 100}%, #333 100%)`,
                              }}
                            />
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Summary cards */}
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-4 pt-4 border-t border-white/10">
                      <div className="rounded-lg p-2 bg-green-500/10 border border-green-500/20 text-center">
                        <div className="text-[10px] text-green-400/60">Monthly Rev</div>
                        <div className="text-sm font-bold text-green-400">{fmtFull(totalRevenue)}</div>
                      </div>
                      <div className="rounded-lg p-2 bg-red-500/10 border border-red-500/20 text-center">
                        <div className="text-[10px] text-red-400/60">Monthly Exp</div>
                        <div className="text-sm font-bold text-red-400">{fmtFull(totalExpenses)}</div>
                      </div>
                      <div className="rounded-lg p-2 border text-center" style={{ borderColor: monthlyProfit >= 0 ? '#22c55e30' : '#ef444430', background: monthlyProfit >= 0 ? '#22c55e08' : '#ef444408' }}>
                        <div className="text-[10px]" style={{ color: monthlyProfit >= 0 ? '#22c55e90' : '#ef444490' }}>Monthly Profit</div>
                        <div className="text-sm font-bold" style={{ color: monthlyProfit >= 0 ? '#22c55e' : '#ef4444' }}>{fmtFull(monthlyProfit)}</div>
                      </div>
                      <div className="rounded-lg p-2 border text-center" style={{ borderColor: `${colors.hexAccent}30`, background: `${colors.hexAccent}08` }}>
                        <div className="text-[10px]" style={{ color: `${colors.hexAccent}90` }}>Annual Profit</div>
                        <div className="text-sm font-bold" style={{ color: colors.hexAccent }}>{fmt(annualProfit)}</div>
                      </div>
                    </div>
                  </div>

                  {/* Financial Goals */}
                  <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                    <h4 className="text-sm font-semibold text-white/90 mb-3 flex items-center gap-1.5">
                      <Target className="h-4 w-4" style={{ color: colors.hexAccent }} />
                      Financial Goals
                    </h4>
                    <div className="grid grid-cols-2 gap-3">
                      {[
                        { key: 'monthlyTarget', label: 'Monthly Target' },
                        { key: 'yearlyTarget', label: 'Yearly Target' },
                        { key: 'savingsTarget', label: 'Savings Goal' },
                        { key: 'investmentAsk', label: 'Investment Ask' },
                      ].map(({ key, label }) => (
                        <div key={key}>
                          <label className="text-[10px] text-white/50 mb-1 block">{label}</label>
                          <div className="relative">
                            <span className="absolute left-2 top-1/2 -translate-y-1/2 text-white/30 text-xs">$</span>
                            <Input
                              type="number"
                              value={goals[key as keyof FinancialGoals]}
                              onChange={e => setGoals(prev => ({ ...prev, [key]: parseInt(e.target.value) || 0 }))}
                              className="bg-black/20 border-white/10 text-white text-xs pl-5 h-8"
                            />
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Goal Progress */}
                    {goals.monthlyTarget > 0 && (
                      <div className="mt-3 pt-3 border-t border-white/10">
                        <div className="flex items-center justify-between text-xs mb-1">
                          <span className="text-white/50">Monthly Target Progress</span>
                          <span className="font-mono" style={{ color: totalRevenue >= goals.monthlyTarget ? '#22c55e' : colors.hexAccent }}>
                            {Math.min(100, Math.round((totalRevenue / goals.monthlyTarget) * 100))}%
                          </span>
                        </div>
                        <div className="h-2 rounded-full bg-white/5 overflow-hidden">
                          <div
                            className="h-full rounded-full transition-all duration-500"
                            style={{
                              width: `${Math.min(100, (totalRevenue / goals.monthlyTarget) * 100)}%`,
                              background: totalRevenue >= goals.monthlyTarget ? '#22c55e' : colors.hexAccent,
                            }}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* ─── BUDGET TAB ─── */}
              {activeTab === 'budget' && (
                <div className="space-y-4">
                  <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                    <h4 className="text-sm font-semibold text-white/90 mb-3 flex items-center gap-1.5">
                      <PieChart className="h-4 w-4" style={{ color: colors.hexAccent }} />
                      Budget Allocation
                    </h4>
                    <p className="text-[10px] text-white/40 mb-4">
                      How would you allocate investment capital? Percentages should total 100%.
                    </p>

                    <div className="grid gap-3">
                      {Object.entries(budgetAlloc).map(([key, value], i) => (
                        <div key={key}>
                          <div className="flex items-center justify-between mb-1">
                            <span className="text-xs text-white/70 capitalize">{key}</span>
                            <span className="text-xs font-mono font-semibold" style={{ color: BUDGET_COLORS[i % BUDGET_COLORS.length] }}>
                              {value}%
                            </span>
                          </div>
                          <input
                            type="range"
                            min={0}
                            max={100}
                            step={5}
                            value={value}
                            onChange={e => setBudgetAlloc(prev => ({ ...prev, [key]: parseInt(e.target.value) }))}
                            className="w-full h-1.5 rounded-full appearance-none cursor-pointer"
                            style={{
                              background: `linear-gradient(to right, ${BUDGET_COLORS[i % BUDGET_COLORS.length]} 0%, ${BUDGET_COLORS[i % BUDGET_COLORS.length]} ${value}%, #333 ${value}%, #333 100%)`,
                            }}
                          />
                        </div>
                      ))}
                    </div>

                    {/* Total check */}
                    <div className="mt-3 pt-3 border-t border-white/10 flex items-center justify-between">
                      <span className="text-xs text-white/60">Total Allocation</span>
                      <span className={`text-sm font-bold ${Object.values(budgetAlloc).reduce((a, b) => a + b, 0) === 100 ? 'text-green-400' : 'text-amber-400'}`}>
                        {Object.values(budgetAlloc).reduce((a, b) => a + b, 0)}%
                        {Object.values(budgetAlloc).reduce((a, b) => a + b, 0) === 100 && <Check className="inline h-3.5 w-3.5 ml-1" />}
                      </span>
                    </div>

                    {/* Dollar amounts if investment ask is set */}
                    {goals.investmentAsk > 0 && (
                      <div className="mt-3 pt-3 border-t border-white/10 space-y-1.5">
                        <div className="text-xs text-white/50 mb-2">Based on {fmtFull(goals.investmentAsk)} investment ask:</div>
                        {Object.entries(budgetAlloc).map(([key, pct], i) => (
                          <div key={key} className="flex items-center justify-between text-xs">
                            <span className="text-white/60 capitalize flex items-center gap-1.5">
                              <div className="w-2 h-2 rounded-full" style={{ background: BUDGET_COLORS[i % BUDGET_COLORS.length] }} />
                              {key}
                            </span>
                            <span className="font-mono text-white/90">{fmtFull(Math.round(goals.investmentAsk * pct / 100))}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Budget Pie Chart */}
                  {budgetPieData.length > 0 && (
                    <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                      <h4 className="text-sm font-semibold text-white/90 mb-3">Allocation Distribution</h4>
                      <ResponsiveContainer width="100%" height={220}>
                        <RechartsPie>
                          <Pie data={budgetPieData} cx="50%" cy="50%" innerRadius={55} outerRadius={85} dataKey="value" label={({ name, value }) => `${name} ${value}%`}>
                            {budgetPieData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
                          </Pie>
                          <Tooltip contentStyle={{ background: '#111', border: '1px solid #333', borderRadius: 8, fontSize: 11 }} />
                        </RechartsPie>
                      </ResponsiveContainer>
                    </div>
                  )}

                  {/* Add category */}
                  {isOwnProfile && (
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => {
                        const name = prompt('New budget category name:');
                        if (name && name.trim()) setBudgetAlloc(prev => ({ ...prev, [name.trim().toLowerCase()]: 0 }));
                      }}
                      className="text-xs w-full border border-dashed border-white/10"
                    >
                      <Plus className="h-3 w-3 mr-1" /> Add Category
                    </Button>
                  )}
                </div>
              )}

              {/* ─── ROADMAP TAB — Dynamic, real-time, connected to artist profile ─── */}
              {activeTab === 'roadmap' && (
                <div className="space-y-4">

                  {/* ══ Real-Time Profile Connection Banner ══ */}
                  <div className="rounded-xl p-3 border flex items-center justify-between" style={{ background: `${colors.hexAccent}10`, borderColor: `${colors.hexAccent}30` }}>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
                      <span className="text-xs text-white/80">
                        {dashboardData?.isLinked ? (
                          <>Engine: <span className="font-bold" style={{ color: colors.hexAccent }}>{dashboardData.engineMode}</span></>
                        ) : (
                          <span className="text-white/50">Economic Engine not linked</span>
                        )}
                        {snapshotData?.snapshot && (
                          <> · Profile: <span className="font-bold" style={{ color: colors.hexAccent }}>{snapshotData.snapshot.profileCompleteness}%</span></>
                        )}
                      </span>
                    </div>
                    {isOwnProfile && (
                      <div className="flex gap-1.5">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => roadmapScanMutation.mutate()}
                          disabled={roadmapScanMutation.isPending}
                          className="text-[10px] h-6 px-2"
                          style={{ color: colors.hexAccent }}
                        >
                          {roadmapScanMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <><Scan className="h-3 w-3 mr-0.5" /> Full Scan</>}
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => adviceMutation.mutate()}
                          disabled={adviceMutation.isPending}
                          className="text-[10px] h-6 px-2"
                          style={{ color: colors.hexAccent }}
                        >
                          {adviceMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <><Bot className="h-3 w-3 mr-0.5" /> AI Advice</>}
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => syncEngineMutation.mutate()}
                          disabled={syncEngineMutation.isPending}
                          className="text-[10px] h-6 px-2"
                          style={{ color: colors.hexAccent }}
                        >
                          {syncEngineMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : '⚡ Sync'}
                        </Button>
                      </div>
                    )}
                  </div>

                  {/* ══ Profile Snapshot Cards ══ */}
                  {snapshotData?.snapshot && (
                    <div className="grid grid-cols-4 sm:grid-cols-6 gap-2">
                      {[
                        { label: 'Songs', value: snapshotData.snapshot.totalSongs, icon: Music, color: '#22c55e' },
                        { label: 'Merch', value: snapshotData.snapshot.totalMerch, icon: ShoppingBag, color: '#f97316' },
                        { label: 'Tokens', value: snapshotData.snapshot.totalTokens, icon: DollarSign, color: '#8b5cf6' },
                        { label: 'Social', value: `${snapshotData.snapshot.socialLinksCount}/6`, icon: Globe, color: '#06b6d4' },
                        { label: 'Vault', value: `$${snapshotData.snapshot.vaultTotal.toFixed(0)}`, icon: CreditCard, color: '#eab308' },
                        { label: 'Profile', value: `${snapshotData.snapshot.profileCompleteness}%`, icon: Activity, color: colors.hexAccent },
                      ].map(({ label, value, icon: Icon, color }) => (
                        <div key={label} className="rounded-lg p-2 text-center bg-black/20 border border-white/5">
                          <Icon className="h-3.5 w-3.5 mx-auto mb-1" style={{ color }} />
                          <div className="text-sm font-bold text-white/90">{value}</div>
                          <div className="text-[9px] text-white/40">{label}</div>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* ══ Last Scan Results ══ */}
                  {scanResult && (
                    <div className="rounded-xl p-3 bg-black/20 border border-white/5 space-y-2">
                      <h4 className="text-xs font-semibold text-white/70 flex items-center gap-1.5">
                        <Scan className="h-3.5 w-3.5" style={{ color: colors.hexAccent }} />
                        Last Scan Results
                      </h4>
                      <div className="grid grid-cols-4 gap-2">
                        <div className="text-center">
                          <div className="text-sm font-bold text-blue-400">{scanResult.milestonesCreated?.length || 0}</div>
                          <div className="text-[9px] text-white/40">New</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-green-400">{scanResult.milestonesUpdated?.length || 0}</div>
                          <div className="text-[9px] text-white/40">Updated</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-amber-400">{scanResult.actionsExecuted?.length || 0}</div>
                          <div className="text-[9px] text-white/40">Actions</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-purple-400">{scanResult.newsGenerated?.length || 0}</div>
                          <div className="text-[9px] text-white/40">News</div>
                        </div>
                      </div>
                      {scanResult.newsGenerated?.length > 0 && (
                        <div className="flex items-center gap-1.5 text-[10px] text-purple-300 bg-purple-500/10 rounded-lg px-2 py-1">
                          <Newspaper className="h-3 w-3" />
                          News published: {scanResult.newsGenerated.join(', ')}
                        </div>
                      )}
                    </div>
                  )}

                  {/* ══ AI Advice ══ */}
                  {aiAdvice && (
                    <div className="rounded-xl p-3 border space-y-1" style={{ background: `${colors.hexAccent}08`, borderColor: `${colors.hexAccent}20` }}>
                      <h4 className="text-xs font-semibold text-white/80 flex items-center gap-1.5">
                        <Bot className="h-3.5 w-3.5" style={{ color: colors.hexAccent }} />
                        AI Roadmap Advisor
                      </h4>
                      <div className="text-[11px] text-white/70 whitespace-pre-line leading-relaxed">{aiAdvice}</div>
                    </div>
                  )}

                  {/* ══ Roadmap Visual Overview (Charts) ══ */}
                  {milestones.length > 0 && (() => {
                    const byCategory = milestones.reduce<Record<string, { total: number; completed: number; in_progress: number; planned: number }>>((acc, m) => {
                      const k = m.category || 'other';
                      if (!acc[k]) acc[k] = { total: 0, completed: 0, in_progress: 0, planned: 0 };
                      acc[k].total += 1;
                      acc[k][m.status] = (acc[k][m.status] || 0) + 1;
                      return acc;
                    }, {});
                    const chartData = Object.entries(byCategory).map(([cat, v]) => ({
                      name: getCategoryMeta(cat).label,
                      color: getCategoryMeta(cat).color,
                      Completed: v.completed,
                      'In Progress': v.in_progress,
                      Planned: v.planned,
                    }));
                    const completedCount = milestones.filter(m => m.status === 'completed').length;
                    const inProgressCount = milestones.filter(m => m.status === 'in_progress').length;
                    const plannedCount = milestones.filter(m => m.status === 'planned').length;
                    const overallProgress = milestones.length > 0 ? (completedCount / milestones.length) * 100 : 0;
                    return (
                      <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                        <div className="flex items-center justify-between mb-3">
                          <h4 className="text-xs font-semibold text-white/80 flex items-center gap-1.5">
                            <BarChart3 className="h-3.5 w-3.5" style={{ color: colors.hexAccent }} />
                            Roadmap Overview
                          </h4>
                          <span className="text-[10px] text-white/50 font-mono">{overallProgress.toFixed(0)}% complete</span>
                        </div>
                        {/* Overall progress bar */}
                        <div className="mb-3">
                          <div className="h-2 rounded-full bg-white/5 overflow-hidden flex">
                            <div className="h-full transition-all" style={{ width: `${(completedCount / milestones.length) * 100}%`, background: 'linear-gradient(90deg, #22c55e, #16a34a)' }} />
                            <div className="h-full transition-all" style={{ width: `${(inProgressCount / milestones.length) * 100}%`, background: `linear-gradient(90deg, ${colors.hexAccent}, ${colors.hexAccent}aa)` }} />
                            <div className="h-full transition-all" style={{ width: `${(plannedCount / milestones.length) * 100}%`, background: 'linear-gradient(90deg, #475569, #334155)' }} />
                          </div>
                          <div className="flex items-center gap-3 mt-1.5 text-[10px] text-white/50">
                            <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-sm bg-green-500" /> {completedCount} completed</span>
                            <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-sm" style={{ background: colors.hexAccent }} /> {inProgressCount} in progress</span>
                            <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-sm bg-slate-500" /> {plannedCount} planned</span>
                          </div>
                        </div>
                        {/* Category stacked bar */}
                        {chartData.length > 0 && (
                          <div className="h-[160px]">
                            <ResponsiveContainer width="100%" height="100%">
                              <BarChart data={chartData} margin={{ top: 5, right: 5, left: -20, bottom: 0 }}>
                                <XAxis dataKey="name" stroke="rgba(255,255,255,0.4)" fontSize={9} />
                                <YAxis stroke="rgba(255,255,255,0.4)" fontSize={9} allowDecimals={false} />
                                <Tooltip contentStyle={{ background: '#0a0612', border: `1px solid ${colors.hexAccent}40`, borderRadius: 8, fontSize: 11 }} />
                                <Legend wrapperStyle={{ fontSize: 10 }} iconSize={8} />
                                <Bar dataKey="Completed" stackId="s" fill="#22c55e" radius={[0, 0, 0, 0]} />
                                <Bar dataKey="In Progress" stackId="s" fill={colors.hexAccent} />
                                <Bar dataKey="Planned" stackId="s" fill="#475569" radius={[4, 4, 0, 0]} />
                              </BarChart>
                            </ResponsiveContainer>
                          </div>
                        )}
                      </div>
                    );
                  })()}

                  {/* ══ Dynamic Milestone Timeline ══ */}
                  <div className="rounded-xl p-4 bg-black/20 border border-white/5">
                    <h4 className="text-sm font-semibold text-white/90 mb-3 flex items-center gap-1.5">
                      <Map className="h-4 w-4" style={{ color: colors.hexAccent }} />
                      Dynamic Career Roadmap
                      <span className="text-[9px] text-white/40 font-normal ml-auto">
                        {milestones.length > 0 && `${milestones.filter(m => m.status === 'completed').length}/${milestones.length} complete`}
                      </span>
                    </h4>

                    {milestones.length === 0 ? (
                      <div className="text-center py-8">
                        <Calendar className="h-10 w-10 mx-auto mb-2 text-white/20" />
                        <p className="text-xs text-white/40 mb-2">No milestones yet.</p>
                        {isOwnProfile && (
                          <Button
                            size="sm"
                            onClick={() => roadmapScanMutation.mutate()}
                            disabled={roadmapScanMutation.isPending}
                            className="text-xs"
                            style={{ background: colors.hexAccent }}
                          >
                            {roadmapScanMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Scan className="h-3 w-3 mr-1" />}
                            Scan Profile & Generate Roadmap
                          </Button>
                        )}
                      </div>
                    ) : (
                      <div className="space-y-3">
                        {milestones.sort((a, b) => {
                          // Sort: in_progress first, then planned, then completed
                          const order = { in_progress: 0, planned: 1, completed: 2 };
                          const diff = (order[a.status] ?? 1) - (order[b.status] ?? 1);
                          return diff !== 0 ? diff : a.date.localeCompare(b.date);
                        }).map((ms, i) => {
                          const progress = ms.targetValue && ms.currentValue !== undefined
                            ? Math.min((ms.currentValue / ms.targetValue) * 100, 100)
                            : null;

                          return (
                            <div key={ms.id || i} className="relative pl-6 pb-3 border-l-2" style={{ borderColor: ms.status === 'completed' ? '#22c55e' : ms.status === 'in_progress' ? colors.hexAccent : '#555' }}>
                              {/* Dot */}
                              <div
                                className="absolute left-[-6px] top-0 w-2.5 h-2.5 rounded-full border-2"
                                style={{
                                  background: ms.status === 'completed' ? '#22c55e' : ms.status === 'in_progress' ? colors.hexAccent : '#333',
                                  borderColor: ms.status === 'completed' ? '#22c55e' : ms.status === 'in_progress' ? colors.hexAccent : '#555',
                                }}
                              />
                              <div className="flex items-start gap-2">
                                <div className="flex-1">
                                  {(() => {
                                    const cat = getCategoryMeta(ms.category);
                                    const CatIcon = cat.icon;
                                    return (
                                      <div className="flex items-center gap-1.5 mb-0.5">
                                        <span className="w-5 h-5 rounded-md flex items-center justify-center flex-shrink-0"
                                          style={{ background: `${cat.color}25`, border: `1px solid ${cat.color}40` }}>
                                          <CatIcon className="h-2.5 w-2.5" style={{ color: cat.color }} />
                                        </span>
                                        {isOwnProfile ? (
                                          <Input
                                            value={ms.title}
                                            onChange={e => updateMilestone(i, 'title', e.target.value)}
                                            placeholder="Milestone title..."
                                            className="bg-transparent border-none text-white text-xs p-0 h-5 font-semibold flex-1"
                                          />
                                        ) : (
                                          <span className="text-xs font-semibold text-white">{ms.title}</span>
                                        )}
                                      </div>
                                    );
                                  })()}

                                  {/* Description */}
                                  {ms.description && (
                                    <p className="text-[10px] text-white/40 mt-0.5 line-clamp-1">{ms.description}</p>
                                  )}

                                  {/* Progress bar for metric-tracked milestones */}
                                  {progress !== null && ms.status !== 'completed' && (
                                    <div className="mt-1.5 flex items-center gap-2">
                                      <div className="flex-1 h-1.5 rounded-full bg-white/10 overflow-hidden">
                                        <div
                                          className="h-full rounded-full transition-all duration-500"
                                          style={{
                                            width: `${progress}%`,
                                            background: `linear-gradient(90deg, ${colors.hexAccent}, ${colors.hexPrimary || colors.hexAccent})`,
                                          }}
                                        />
                                      </div>
                                      <span className="text-[9px] text-white/50 font-mono min-w-[30px] text-right">
                                        {ms.currentValue}/{ms.targetValue}
                                      </span>
                                    </div>
                                  )}

                                  <div className="flex items-center gap-2 mt-1 flex-wrap">
                                    {isOwnProfile ? (
                                      <>
                                        <input
                                          type="date"
                                          value={ms.date}
                                          onChange={e => updateMilestone(i, 'date', e.target.value)}
                                          className="text-[10px] bg-transparent border-none text-white/50 outline-none"
                                        />
                                        <select
                                          value={ms.status}
                                          onChange={e => updateMilestone(i, 'status', e.target.value)}
                                          className="text-[10px] bg-transparent border-none outline-none"
                                          style={{ color: ms.status === 'completed' ? '#22c55e' : ms.status === 'in_progress' ? colors.hexAccent : '#999' }}
                                        >
                                          <option value="planned">Planned</option>
                                          <option value="in_progress">In Progress</option>
                                          <option value="completed">Completed</option>
                                        </select>
                                        <select
                                          value={ms.category}
                                          onChange={e => updateMilestone(i, 'category', e.target.value)}
                                          className="text-[10px] bg-transparent border-none text-white/40 outline-none"
                                        >
                                          <option value="release">Release</option>
                                          <option value="tour">Tour</option>
                                          <option value="marketing">Marketing</option>
                                          <option value="financial">Financial</option>
                                          <option value="branding">Branding</option>
                                          <option value="collaboration">Collaboration</option>
                                          <option value="engine">Economic Engine</option>
                                          <option value="growth">Growth</option>
                                          <option value="music">Music</option>
                                          <option value="revenue">Revenue</option>
                                        </select>
                                      </>
                                    ) : (
                                      <>
                                        <span className="text-[10px] text-white/40">{ms.date}</span>
                                        <span className="text-[10px]" style={{ color: ms.status === 'completed' ? '#22c55e' : ms.status === 'in_progress' ? colors.hexAccent : '#999' }}>
                                          {ms.status.replace('_', ' ')}
                                        </span>
                                      </>
                                    )}
                                    {ms.priority && ms.priority !== 'medium' && (
                                      <span className={`text-[9px] px-1.5 py-0.5 rounded-full font-medium ${
                                        ms.priority === 'critical' ? 'bg-red-500/20 text-red-400' :
                                        ms.priority === 'high' ? 'bg-orange-500/20 text-orange-400' :
                                        'bg-zinc-500/20 text-zinc-400'
                                      }`}>
                                        {ms.priority}
                                      </span>
                                    )}
                                    {ms.linkedToEngine && (
                                      <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-yellow-500/20 text-yellow-400 font-medium">⚡ Engine</span>
                                    )}
                                    {ms.autoGenerated && (
                                      <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-blue-500/20 text-blue-400 font-medium">Auto</span>
                                    )}
                                    {ms.newsPublished && (
                                      <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-purple-500/20 text-purple-400 font-medium">📰 News</span>
                                    )}
                                    {ms.action?.executedAt && (
                                      <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 font-medium">✓ Action</span>
                                    )}
                                  </div>
                                </div>
                                {isOwnProfile && (
                                  <button onClick={() => removeMilestone(i)} className="text-white/20 hover:text-red-400 transition-colors">
                                    <Trash2 className="h-3.5 w-3.5" />
                                  </button>
                                )}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    )}

                    {isOwnProfile && (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={addMilestone}
                        className="text-xs w-full mt-3 border border-dashed border-white/10"
                      >
                        <Plus className="h-3 w-3 mr-1" /> Add Milestone
                      </Button>
                    )}
                  </div>

                  {/* ══ Milestone Stats ══ */}
                  {milestones.length > 0 && (
                    <div className="grid grid-cols-4 gap-3">
                      <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                        <div className="text-lg font-bold text-white/90">{milestones.length}</div>
                        <div className="text-[10px] text-white/50">Total</div>
                      </div>
                      <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                        <div className="text-lg font-bold text-green-400">{milestones.filter(m => m.status === 'completed').length}</div>
                        <div className="text-[10px] text-green-400/50">Done</div>
                      </div>
                      <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                        <div className="text-lg font-bold" style={{ color: colors.hexAccent }}>{milestones.filter(m => m.status === 'in_progress').length}</div>
                        <div className="text-[10px]" style={{ color: `${colors.hexAccent}80` }}>Active</div>
                      </div>
                      <div className="rounded-xl p-3 bg-black/20 border border-white/5 text-center">
                        <div className="text-lg font-bold text-purple-400">{milestones.filter(m => m.newsPublished).length}</div>
                        <div className="text-[10px] text-purple-400/50">News</div>
                      </div>
                    </div>
                  )}

                  {/* ══ Execution Log (last 5) ══ */}
                  {scanResult?.executionLog && scanResult.executionLog.length > 0 && (
                    <div className="rounded-xl p-3 bg-black/20 border border-white/5 space-y-1.5">
                      <h4 className="text-[10px] text-white/50 uppercase tracking-wider font-semibold">Execution Log</h4>
                      {(scanResult.executionLog as any[]).slice(-5).reverse().map((log: any, i: number) => (
                        <div key={i} className="flex items-center gap-2 text-[10px] text-white/60">
                          <span className={`w-1.5 h-1.5 rounded-full ${log.event === 'auto_completed' ? 'bg-green-400' : 'bg-blue-400'}`} />
                          <span className="flex-1 truncate">{log.details || log.event}</span>
                          <span className="text-white/30 text-[9px]">{new Date(log.timestamp).toLocaleDateString()}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* ─── PITCH DECK TAB ─── */}
              {activeTab === 'pitch' && (
                <div className="space-y-4">
                  {/* Generate button */}
                  {isOwnProfile && (
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-semibold text-white/90 flex items-center gap-1.5">
                        <Presentation className="h-4 w-4" style={{ color: colors.hexAccent }} />
                        Investor Pitch Deck
                      </h4>
                      <Button
                        size="sm"
                        onClick={() => pitchMutation.mutate()}
                        disabled={pitchMutation.isPending}
                        className="text-xs"
                        style={{ background: colors.hexAccent }}
                      >
                        {pitchMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Sparkles className="h-3 w-3 mr-1" />}
                        Generate with AI
                      </Button>
                    </div>
                  )}

                  {planData?.pitchDeckData ? (
                    <PitchDeckSlides
                      pitchData={planData.pitchDeckData}
                      artistName={businessName || artistName}
                      colors={colors}
                      fallbackImageUrl={planData.pitchDeckData.coverImageUrl || null}
                    />
                  ) : (
                    <div className="text-center py-12 rounded-xl bg-black/20 border border-white/5">
                      <Presentation className="h-12 w-12 mx-auto mb-3 text-white/20" />
                      <p className="text-sm text-white/40 mb-1">No pitch deck generated yet</p>
                      <p className="text-xs text-white/30">Fill in your financials and click "Generate with AI" to create your investor pitch</p>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}
