/**
 * BUSINESS PLAN ↔ ECONOMIC ENGINE BRIDGE
 * 
 * Connects the Business Plan module with the Economic Engine L3.
 * - Syncs economic engine data into business plan projections
 * - Auto-updates roadmap milestones based on artist activity
 * - Generates news for important achievements
 * - Provides dynamic roadmap execution tracking
 */

import { db } from '../db';
import {
  artistBusinessPlans, artistEconomicProfile, artistTreasuryVault,
  treasuryTransactions, users, songs, artistNews, newsArticles,
  economicEngineAuditLog,
} from '../../db/schema';
import { eq, desc, sql, and, gte, count } from 'drizzle-orm';
import { enqueueNewsEvent } from './news-event-orchestrator';

// ═══════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════

interface RoadmapMilestone {
  id?: string;
  title: string;
  date: string;
  category: string;
  status: 'planned' | 'in_progress' | 'completed';
  description?: string;
  completedAt?: string;
  autoGenerated?: boolean;
  linkedToEngine?: boolean;
  priority?: 'low' | 'medium' | 'high' | 'critical';
}

interface ExecutionLogEntry {
  milestoneId: string;
  event: string;
  plannedDate: string;
  actualDate?: string;
  delta?: number;
  details?: string;
  timestamp: string;
}

// ═══════════════════════════════════════════
// SYNC: Economic Engine → Business Plan
// ═══════════════════════════════════════════

/**
 * Syncs economic engine data into the business plan projections.
 * Called after each economic cycle or on-demand.
 */
export async function syncEngineToBusinessPlan(artistId: number): Promise<void> {
  try {
    // Get economic profile and vault
    const [profile] = await db.select().from(artistEconomicProfile)
      .where(eq(artistEconomicProfile.artistId, artistId)).limit(1);
    const [vault] = await db.select().from(artistTreasuryVault)
      .where(eq(artistTreasuryVault.artistId, artistId)).limit(1);

    if (!profile || !vault) return;

    // Get or create business plan
    let [plan] = await db.select().from(artistBusinessPlans)
      .where(eq(artistBusinessPlans.artistId, artistId)).limit(1);

    if (!plan) {
      // Auto-create minimal business plan linked to engine
      const [artist] = await db.select({
        name: users.firstName,
        lastName: users.lastName,
      }).from(users).where(eq(users.id, artistId)).limit(1);

      const artistName = artist ? `${artist.name || ''} ${artist.lastName || ''}`.trim() : 'Artist';

      [plan] = await db.insert(artistBusinessPlans).values({
        artistId,
        businessName: `${artistName} Music`,
        linkedEngineMode: profile.operatingMode || 'stable',
        roadmapAutoUpdate: true,
        milestones: generateDefaultMilestones(profile.operatingMode || 'stable'),
        roadmapExecutionLog: [],
      }).returning();
    }

    // Update linked engine mode
    const totalVault = Number(vault.operationBalance || 0) +
      Number(vault.reserveBalance || 0) +
      Number(vault.growthBalance || 0) +
      Number(vault.defiBalance || 0);

    // Sync revenue data from vault transactions (last 30 days)
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const [txSums] = await db.select({
      totalIncome: sql<number>`COALESCE(SUM(CASE WHEN ${treasuryTransactions.type} = 'income' THEN ${treasuryTransactions.amount} ELSE 0 END), 0)`,
      totalExpense: sql<number>`COALESCE(SUM(CASE WHEN ${treasuryTransactions.type} = 'expense' THEN ${treasuryTransactions.amount} ELSE 0 END), 0)`,
    })
    .from(treasuryTransactions)
    .where(and(
      eq(treasuryTransactions.artistId, artistId),
      gte(treasuryTransactions.createdAt, thirtyDaysAgo)
    ));

    const monthlyRevenue = Number(txSums?.totalIncome || 0);
    const monthlyExpenses = Number(txSums?.totalExpense || 0);

    // Generate 12-month projections based on current vault data
    const projections = generateProjections(
      monthlyRevenue,
      monthlyExpenses,
      profile.operatingMode || 'stable',
      totalVault
    );

    await db.update(artistBusinessPlans).set({
      linkedEngineMode: profile.operatingMode,
      projections,
      updatedAt: new Date(),
    }).where(eq(artistBusinessPlans.artistId, artistId));

  } catch (error) {
    console.error(`[Bridge] Error syncing engine to business plan for artist ${artistId}:`, error);
  }
}

// ═══════════════════════════════════════════
// DYNAMIC ROADMAP AUTO-UPDATE
// ═══════════════════════════════════════════

/**
 * Checks artist activity and auto-updates milestone statuses.
 * Should be called periodically (e.g., every hour or after key actions).
 */
export async function updateDynamicRoadmap(artistId: number): Promise<{ updated: string[] }> {
  const updatedMilestones: string[] = [];

  try {
    const [plan] = await db.select().from(artistBusinessPlans)
      .where(eq(artistBusinessPlans.artistId, artistId)).limit(1);

    if (!plan || !plan.roadmapAutoUpdate) return { updated: [] };

    const milestones: RoadmapMilestone[] = (plan.milestones as RoadmapMilestone[]) || [];
    const executionLog: ExecutionLogEntry[] = (plan.roadmapExecutionLog as ExecutionLogEntry[]) || [];
    const now = new Date();

    // Get artist activity data
    const [songCount] = await db.select({ count: count() }).from(songs)
      .where(eq(songs.userId, artistId));

    const [vault] = await db.select().from(artistTreasuryVault)
      .where(eq(artistTreasuryVault.artistId, artistId)).limit(1);

    const [profile] = await db.select().from(artistEconomicProfile)
      .where(eq(artistEconomicProfile.artistId, artistId)).limit(1);

    const totalSongs = Number(songCount?.count || 0);
    const totalVault = vault ? Number(vault.operationBalance || 0) +
      Number(vault.reserveBalance || 0) +
      Number(vault.growthBalance || 0) +
      Number(vault.defiBalance || 0) : 0;

    // Check each planned/in_progress milestone against actual data
    for (let i = 0; i < milestones.length; i++) {
      const m = milestones[i];
      if (m.status === 'completed') continue;

      const milestoneId = m.id || `milestone-${i}`;
      let shouldComplete = false;
      let shouldStartProgress = false;

      // Auto-detect milestone completion based on category
      switch (m.category) {
        case 'release':
        case 'music':
          // Check if songs target met
          const targetSongs = extractNumberFromTitle(m.title) || 5;
          if (totalSongs >= targetSongs) shouldComplete = true;
          else if (totalSongs >= targetSongs * 0.5) shouldStartProgress = true;
          break;

        case 'financial':
        case 'revenue':
          // Check vault balance targets
          const targetAmount = extractNumberFromTitle(m.title) || 1000;
          if (totalVault >= targetAmount) shouldComplete = true;
          else if (totalVault >= targetAmount * 0.5) shouldStartProgress = true;
          break;

        case 'engine':
        case 'economic':
          // Check if engine mode reached target
          if (profile?.isEnabled && m.title.toLowerCase().includes(profile.operatingMode || '')) {
            shouldComplete = true;
          }
          break;

        case 'growth':
          // Time-based milestones — check if date has passed
          if (new Date(m.date) <= now && m.status === 'in_progress') {
            shouldStartProgress = true; // Mark as needs review
          }
          break;
      }

      // Update milestone status
      if (shouldComplete && m.status !== 'completed') {
        milestones[i] = {
          ...m,
          id: milestoneId,
          status: 'completed',
          completedAt: now.toISOString(),
        };
        updatedMilestones.push(m.title);

        executionLog.push({
          milestoneId,
          event: 'auto_completed',
          plannedDate: m.date,
          actualDate: now.toISOString(),
          delta: Math.round((now.getTime() - new Date(m.date).getTime()) / (1000 * 60 * 60 * 24)),
          details: `Milestone "${m.title}" auto-completed by system`,
          timestamp: now.toISOString(),
        });

        // Generate news for completed milestone
        await generateMilestoneNews(artistId, m);
      } else if (shouldStartProgress && m.status === 'planned') {
        milestones[i] = { ...m, id: milestoneId, status: 'in_progress' };

        executionLog.push({
          milestoneId,
          event: 'auto_started',
          plannedDate: m.date,
          details: `Milestone "${m.title}" auto-started — progress detected`,
          timestamp: now.toISOString(),
        });
      }
    }

    // Auto-generate new milestones if all current ones are completed
    const activeMilestones = milestones.filter(m => m.status !== 'completed');
    if (activeMilestones.length === 0 && milestones.length > 0) {
      const newMilestones = generateNextPhaseMilestones(
        profile?.operatingMode || 'stable',
        totalSongs,
        totalVault
      );
      milestones.push(...newMilestones);
    }

    // Save updates
    if (updatedMilestones.length > 0 || activeMilestones.length === 0) {
      await db.update(artistBusinessPlans).set({
        milestones,
        roadmapExecutionLog: executionLog.slice(-100), // Keep last 100 entries
        lastRoadmapSync: now,
        updatedAt: now,
      }).where(eq(artistBusinessPlans.artistId, artistId));
    }

    return { updated: updatedMilestones };
  } catch (error) {
    console.error(`[Bridge] Error updating roadmap for artist ${artistId}:`, error);
    return { updated: [] };
  }
}

// ═══════════════════════════════════════════
// NEWS AUTO-GENERATION FOR IMPORTANT EVENTS
// ═══════════════════════════════════════════

/**
 * Generates news for a completed milestone.
 * Creates entry in both artistNews (artist section) and main newsArticles.
 */
async function generateMilestoneNews(artistId: number, milestone: RoadmapMilestone): Promise<void> {
  try {
    const [artist] = await db.select({
      name: users.firstName,
      lastName: users.lastName,
      bio: users.biography,
      genre: users.genres,
    }).from(users).where(eq(users.id, artistId)).limit(1);

    if (!artist) return;

    const artistName = `${artist.name || ''} ${artist.lastName || ''}`.trim();

    // Use the news event orchestrator for cross-posting
    enqueueNewsEvent({
      type: 'milestone_reached',
      artistId,
      artistName,
      artistBio: artist.bio || undefined,
      genre: Array.isArray(artist.genre) ? artist.genre[0] : undefined,
      details: {
        milestoneTitle: milestone.title,
        milestoneCategory: milestone.category,
        milestoneDescription: milestone.description,
        priority: milestone.priority || 'medium',
      },
    });

    console.log(`[Bridge] News event enqueued for milestone: "${milestone.title}" (artist ${artistId})`);
  } catch (error) {
    console.error(`[Bridge] Error generating milestone news for artist ${artistId}:`, error);
  }
}

/**
 * Generates news when economic engine mode changes.
 * Called from the economic engine when operating mode transitions happen.
 */
export async function generateEngineModeChangeNews(
  artistId: number,
  oldMode: string,
  newMode: string
): Promise<void> {
  try {
    const [artist] = await db.select({
      name: users.firstName,
      lastName: users.lastName,
      bio: users.biography,
    }).from(users).where(eq(users.id, artistId)).limit(1);

    if (!artist) return;

    const artistName = `${artist.name || ''} ${artist.lastName || ''}`.trim();

    enqueueNewsEvent({
      type: 'milestone_reached',
      artistId,
      artistName,
      artistBio: artist.bio || undefined,
      details: {
        milestoneTitle: `Economic Engine upgraded: ${oldMode} → ${newMode}`,
        milestoneCategory: 'engine',
        milestoneDescription: `${artistName}'s economic engine has transitioned from ${oldMode} mode to ${newMode} mode, reflecting their growing financial strategy.`,
        priority: 'high',
      },
    });
  } catch (error) {
    console.error(`[Bridge] Error generating engine mode change news:`, error);
  }
}

/**
 * Generates news when vault reaches a significant threshold.
 */
export async function generateVaultThresholdNews(
  artistId: number,
  threshold: number,
  totalVault: number
): Promise<void> {
  try {
    const [artist] = await db.select({
      name: users.firstName,
      lastName: users.lastName,
    }).from(users).where(eq(users.id, artistId)).limit(1);

    if (!artist) return;

    const artistName = `${artist.name || ''} ${artist.lastName || ''}`.trim();

    enqueueNewsEvent({
      type: 'milestone_reached',
      artistId,
      artistName,
      details: {
        milestoneTitle: `Treasury vault reached $${threshold.toLocaleString()}`,
        milestoneCategory: 'financial',
        milestoneDescription: `${artistName}'s treasury vault has crossed the $${threshold.toLocaleString()} mark with a total balance of $${totalVault.toFixed(2)}.`,
        priority: 'high',
      },
    });
  } catch (error) {
    console.error(`[Bridge] Error generating vault threshold news:`, error);
  }
}

// ═══════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════

function generateDefaultMilestones(mode: string): RoadmapMilestone[] {
  const now = new Date();
  const milestones: RoadmapMilestone[] = [];

  const addMonths = (date: Date, months: number) => {
    const d = new Date(date);
    d.setMonth(d.getMonth() + months);
    return d.toISOString().split('T')[0];
  };

  // Phase 1: Foundation (months 1-3)
  milestones.push(
    {
      id: 'default-1',
      title: 'Release first 3 songs',
      date: addMonths(now, 1),
      category: 'release',
      status: 'planned',
      description: 'Upload and publish your first 3 songs on the platform',
      autoGenerated: true,
      linkedToEngine: false,
      priority: 'high',
    },
    {
      id: 'default-2',
      title: 'Complete business plan profile',
      date: addMonths(now, 1),
      category: 'growth',
      status: 'planned',
      description: 'Fill in revenue streams, expenses, and financial goals',
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'high',
    },
    {
      id: 'default-3',
      title: 'Activate Economic Engine',
      date: addMonths(now, 2),
      category: 'engine',
      status: mode !== 'survival' ? 'in_progress' : 'planned',
      description: 'Enable the economic engine to start optimizing your treasury',
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'critical',
    },
  );

  // Phase 2: Growth (months 3-6)
  milestones.push(
    {
      id: 'default-4',
      title: 'Reach $500 in treasury vault',
      date: addMonths(now, 3),
      category: 'financial',
      status: 'planned',
      description: 'Accumulate $500 across all vault buckets',
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'medium',
    },
    {
      id: 'default-5',
      title: 'Release 10 songs total',
      date: addMonths(now, 4),
      category: 'release',
      status: 'planned',
      description: 'Build a catalog of 10 published songs',
      autoGenerated: true,
      linkedToEngine: false,
      priority: 'medium',
    },
    {
      id: 'default-6',
      title: 'Launch merchandise store',
      date: addMonths(now, 5),
      category: 'growth',
      status: 'planned',
      description: 'Set up and customize your merchandise offerings',
      autoGenerated: true,
      linkedToEngine: false,
      priority: 'medium',
    },
  );

  // Phase 3: Expansion (months 6-12)
  milestones.push(
    {
      id: 'default-7',
      title: 'Engine expansion mode',
      date: addMonths(now, 6),
      category: 'engine',
      status: 'planned',
      description: 'Transition economic engine to expansion operating mode',
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'medium',
    },
    {
      id: 'default-8',
      title: 'Reach $5,000 in treasury vault',
      date: addMonths(now, 9),
      category: 'financial',
      status: 'planned',
      description: 'Scale treasury to $5,000 for sustainable growth',
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'low',
    },
  );

  return milestones;
}

function generateNextPhaseMilestones(
  mode: string,
  currentSongs: number,
  currentVault: number
): RoadmapMilestone[] {
  const now = new Date();
  const milestones: RoadmapMilestone[] = [];

  const addMonths = (date: Date, months: number) => {
    const d = new Date(date);
    d.setMonth(d.getMonth() + months);
    return d.toISOString().split('T')[0];
  };

  const nextSongTarget = Math.ceil((currentSongs + 5) / 5) * 5;
  const nextVaultTarget = currentVault < 1000 ? 1000 :
    currentVault < 5000 ? 5000 :
    currentVault < 10000 ? 10000 :
    Math.ceil(currentVault / 10000) * 10000 + 10000;

  milestones.push(
    {
      id: `auto-${Date.now()}-1`,
      title: `Release ${nextSongTarget} songs total`,
      date: addMonths(now, 3),
      category: 'release',
      status: 'planned',
      description: `Continue building your catalog to ${nextSongTarget} songs`,
      autoGenerated: true,
      priority: 'medium',
    },
    {
      id: `auto-${Date.now()}-2`,
      title: `Reach $${nextVaultTarget.toLocaleString()} in treasury`,
      date: addMonths(now, 6),
      category: 'financial',
      status: 'planned',
      description: `Scale treasury vault to $${nextVaultTarget.toLocaleString()}`,
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'high',
    },
  );

  // Mode-specific milestone
  const nextMode = mode === 'survival' ? 'stable' :
    mode === 'stable' ? 'expansion' :
    mode === 'expansion' ? 'aggressive' : 'aggressive';

  if (mode !== 'aggressive') {
    milestones.push({
      id: `auto-${Date.now()}-3`,
      title: `Upgrade engine to ${nextMode} mode`,
      date: addMonths(now, 4),
      category: 'engine',
      status: 'planned',
      description: `Transition economic engine from ${mode} to ${nextMode} operating mode`,
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'high',
    });
  }

  return milestones;
}

function generateProjections(
  monthlyRevenue: number,
  monthlyExpenses: number,
  mode: string,
  currentVault: number
): Array<{ month: string; revenue: number; expenses: number; profit: number }> {
  const projections: Array<{ month: string; revenue: number; expenses: number; profit: number }> = [];
  const now = new Date();

  // Growth rates by mode
  const growthRates: Record<string, number> = {
    survival: 0.02,
    stable: 0.05,
    expansion: 0.10,
    aggressive: 0.15,
    defense: 0.01,
  };

  const growthRate = growthRates[mode] || 0.05;
  let revenue = monthlyRevenue || 100;
  let expenses = monthlyExpenses || 50;

  for (let i = 0; i < 12; i++) {
    const date = new Date(now);
    date.setMonth(date.getMonth() + i + 1);

    revenue = Math.round(revenue * (1 + growthRate) * 100) / 100;
    expenses = Math.round(expenses * (1 + growthRate * 0.5) * 100) / 100; // Expenses grow slower

    projections.push({
      month: date.toISOString().slice(0, 7),
      revenue: Math.round(revenue * 100) / 100,
      expenses: Math.round(expenses * 100) / 100,
      profit: Math.round((revenue - expenses) * 100) / 100,
    });
  }

  return projections;
}

function extractNumberFromTitle(title: string): number | null {
  const match = title.match(/\$?([\d,]+)/);
  if (match) {
    return parseInt(match[1].replace(/,/g, ''), 10);
  }
  return null;
}

// ═══════════════════════════════════════════
// API HELPER: Get combined dashboard data
// ═══════════════════════════════════════════

/**
 * Returns combined data from both business plan and economic engine
 * for the artist dashboard integration view.
 */
export async function getCombinedDashboardData(artistId: number) {
  const [plan] = await db.select().from(artistBusinessPlans)
    .where(eq(artistBusinessPlans.artistId, artistId)).limit(1);
  const [profile] = await db.select().from(artistEconomicProfile)
    .where(eq(artistEconomicProfile.artistId, artistId)).limit(1);
  const [vault] = await db.select().from(artistTreasuryVault)
    .where(eq(artistTreasuryVault.artistId, artistId)).limit(1);

  return {
    businessPlan: plan || null,
    engineProfile: profile || null,
    vault: vault || null,
    isLinked: !!(plan && profile?.isEnabled),
    engineMode: profile?.operatingMode || 'none',
    totalVault: vault ? Number(vault.operationBalance || 0) +
      Number(vault.reserveBalance || 0) +
      Number(vault.growthBalance || 0) +
      Number(vault.defiBalance || 0) : 0,
    milestones: {
      total: ((plan?.milestones as RoadmapMilestone[]) || []).length,
      completed: ((plan?.milestones as RoadmapMilestone[]) || []).filter(m => m.status === 'completed').length,
      inProgress: ((plan?.milestones as RoadmapMilestone[]) || []).filter(m => m.status === 'in_progress').length,
      planned: ((plan?.milestones as RoadmapMilestone[]) || []).filter(m => m.status === 'planned').length,
    },
  };
}
