/**
 * External Action Router
 * Any AI agent or chat (C-Suite, Hermes, Agent Gateway, etc.) can call this
 * to detect user intent and dispatch actions to external platforms.
 *
 * Usage:
 *   import { handleExternalActionIntent } from '../services/external-action-router';
 *   const result = await handleExternalActionIntent(userId, userMessage, context);
 *   // Returns { handled: true, action, message } or { handled: false }
 */

import { neon } from "@neondatabase/serverless";
import { queueExternalPost } from "./external-publish-service";

const getSql = () => neon(process.env.DATABASE_URL!);

export interface ExternalActionContext {
  /** Content to post/send (already generated by the AI) */
  generatedContent?: string;
  imageUrl?: string;
  videoUrl?: string;
  songTitle?: string;
  artistName?: string;
  targetEmails?: string[]; // for direct email blasts
}

export interface ExternalActionResult {
  handled: boolean;
  action?: string;
  message?: string;
  queueId?: number | null;
}

/** Detect if a user message contains an intent to publish or send externally */
export async function handleExternalActionIntent(
  userId: number,
  userMessage: string,
  context: ExternalActionContext = {}
): Promise<ExternalActionResult> {
  const msg = userMessage.toLowerCase();

  // ── Instagram post ────────────────────────────────────────────────────────
  if (
    msg.includes("postea") ||
    msg.includes("publica") ||
    (msg.includes("instagram") && (msg.includes("post") || msg.includes("sube"))) ||
    msg.includes("publish to instagram") ||
    msg.includes("post to instagram")
  ) {
    const caption = context.generatedContent || userMessage;
    const id = await queueExternalPost({
      sourceType: "agent_post",
      sourceId: Date.now(), // ephemeral ID for agent-generated posts
      platform: "instagram",
      userId,
      caption,
      imageUrl: context.imageUrl,
      videoUrl: context.videoUrl,
      hashtags: extractHashtags(caption),
      priority: 3,
    });

    if (id === null) {
      return {
        handled: true,
        action: "instagram_post_failed",
        message:
          "No encontré una extensión de Instagram activa para tu cuenta. Ve a Configuración → Chrome Extension y conéctala primero.",
      };
    }

    return {
      handled: true,
      action: "instagram_post_queued",
      queueId: id,
      message: `✅ Post encolado para Instagram. La Chrome Extension lo publicará en el próximo ciclo de sync (aprox. 5 min). ID de cola: ${id}`,
    };
  }

  // ── YouTube post ──────────────────────────────────────────────────────────
  if (
    (msg.includes("youtube") || msg.includes("yt")) &&
    (msg.includes("sube") || msg.includes("publica") || msg.includes("post") || msg.includes("upload"))
  ) {
    const caption = context.generatedContent || userMessage;
    const id = await queueExternalPost({
      sourceType: "agent_post",
      sourceId: Date.now(),
      platform: "youtube",
      userId,
      caption,
      videoUrl: context.videoUrl,
      priority: 3,
    });

    return {
      handled: true,
      action: id ? "youtube_post_queued" : "youtube_no_extension",
      queueId: id,
      message: id
        ? `✅ Video encolado para YouTube. La Chrome Extension lo subirá en el próximo sync.`
        : "No tienes la extensión de YouTube conectada. Ve a Configuración → YouTube Extension.",
    };
  }

  // ── Email blast a fans ────────────────────────────────────────────────────
  if (
    (msg.includes("email") || msg.includes("correo") || msg.includes("manda")) &&
    (msg.includes("fan") || msg.includes("seguidore") || msg.includes("suscriptor") || msg.includes("follower"))
  ) {
    const sql = getSql();
    const body = context.generatedContent || userMessage;

    // Get artist's social_user id
    const [su] = await sql`SELECT id FROM social_users WHERE real_user_id=${userId} LIMIT 1`.catch(() => []);
    if (!su) {
      return {
        handled: true,
        action: "email_blast_no_profile",
        message: "No encontré tu perfil en la red social. Sincroniza tu cuenta primero.",
      };
    }

    // Get followers with email
    const followers = await sql`
      SELECT su2.email, su2.id
      FROM social_follows sf
      JOIN social_users su2 ON su2.id = sf.follower_id
      WHERE sf.following_id = ${su.id}
        AND su2.email IS NOT NULL
        AND su2.email_notifications_enabled = TRUE
      LIMIT 1000
    `;

    if (!followers.length) {
      return {
        handled: true,
        action: "email_blast_no_followers",
        message: "Aún no tienes seguidores con email registrado en la plataforma.",
      };
    }

    // Queue notifications for each follower
    const { queueSocialNotification } = await import("./social-notification-service");
    for (const fan of followers) {
      await queueSocialNotification({
        recipientUserId: fan.id,
        recipientEmail: fan.email,
        type: "platform_event",
        actorName: context.artistName || "Tu artista favorito",
        extraData: {
          title: "📢 Mensaje de tu artista",
          body,
          ctaText: "Ver en Boostify",
          ctaUrl: process.env.APP_URL || "https://www.boostifymusic.com",
        },
      });
    }

    return {
      handled: true,
      action: "email_blast_queued",
      message: `✅ Email encolado para ${followers.length} seguidores. Se enviará en el próximo ciclo (aprox. 1 min).`,
    };
  }

  return { handled: false };
}

function extractHashtags(text: string): string[] {
  const found = text.match(/#\w+/g) || [];
  return found.map((h) => h.replace("#", "")).slice(0, 15);
}
