/**
 * DYNAMIC ROADMAP ENGINE — Real-Time Artist Profile → Milestones → Actions → News
 * 
 * Scans the artist's full profile in real-time:
 *   songs, tokens, merch, social links, vault, engine mode, community, followers
 * 
 * Auto-generates smart milestones based on actual profile state,
 * executes platform actions when milestones trigger,
 * and publishes news articles for every significant event.
 */

import { db } from '../db';
import {
  artistBusinessPlans, artistEconomicProfile, artistTreasuryVault,
  users, songs, merchandise, tokenizedSongs, artistNews,
} from '../../db/schema';
import { eq, desc, sql, count } from 'drizzle-orm';
import { enqueueNewsEvent, NewsEventPayload } from './news-event-orchestrator';
import OpenAI from 'openai';
import { PRIMARY_MODEL } from '../utils/ai-config';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY || '' });

// ═══════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════

export interface RoadmapMilestone {
  id: string;
  title: string;
  date: string;
  category: string;
  status: 'planned' | 'in_progress' | 'completed';
  description?: string;
  completedAt?: string;
  autoGenerated?: boolean;
  linkedToEngine?: boolean;
  priority?: 'low' | 'medium' | 'high' | 'critical';
  /** The profile metric that drives this milestone */
  profileMetric?: string;
  /** Target value for auto-completion */
  targetValue?: number;
  /** Current value (updated on scan) */
  currentValue?: number;
  /** Action to execute when milestone completes */
  action?: RoadmapAction;
  /** News was published for this milestone */
  newsPublished?: boolean;
}

export interface RoadmapAction {
  type: 'publish_news' | 'send_notification' | 'trigger_campaign' | 'update_profile' | 'generate_content';
  payload?: Record<string, any>;
  executedAt?: string;
  result?: string;
}

export interface ProfileSnapshot {
  artistId: number;
  artistName: string;
  slug: string;
  genre: string;
  biography: string;
  country?: string;
  profileImage?: string;
  // Counts
  totalSongs: number;
  totalMerch: number;
  totalTokens: number;
  // Social links filled
  hasSpotify: boolean;
  hasInstagram: boolean;
  hasTwitter: boolean;
  hasYoutube: boolean;
  hasTikTok: boolean;
  hasFacebook: boolean;
  socialLinksCount: number;
  // Economic
  engineEnabled: boolean;
  engineMode: string;
  vaultTotal: number;
  vaultOperation: number;
  vaultReserve: number;
  vaultGrowth: number;
  vaultDefi: number;
  // Profile completeness (0-100)
  profileCompleteness: number;
  // Business plan
  hasBiography: boolean;
  hasBusinessPlan: boolean;
  hasPitchDeck: boolean;
  hasExecutiveSummary: boolean;
  // Timestamp
  scannedAt: string;
}

export interface RoadmapScanResult {
  snapshot: ProfileSnapshot;
  milestonesUpdated: string[];
  milestonesCreated: string[];
  actionsExecuted: string[];
  newsGenerated: string[];
}

// ═══════════════════════════════════════════
// PROFILE SCANNER — Read artist state in real-time
// ═══════════════════════════════════════════

export async function scanArtistProfile(artistId: number): Promise<ProfileSnapshot> {
  // 1. Artist data
  const [artist] = await db.select().from(users).where(eq(users.id, artistId)).limit(1);
  if (!artist) throw new Error(`Artist ${artistId} not found`);

  // 2. Song count
  const [songCount] = await db.select({ count: count() }).from(songs)
    .where(eq(songs.userId, artistId));

  // 3. Merchandise count
  const [merchCount] = await db.select({ count: count() }).from(merchandise)
    .where(eq(merchandise.userId, artistId));

  // 4. Token count
  const [tokenCount] = await db.select({ count: count() }).from(tokenizedSongs)
    .where(eq(tokenizedSongs.artistId, artistId));

  // 5. Economic engine + vault
  const [profile] = await db.select().from(artistEconomicProfile)
    .where(eq(artistEconomicProfile.artistId, artistId)).limit(1);
  const [vault] = await db.select().from(artistTreasuryVault)
    .where(eq(artistTreasuryVault.artistId, artistId)).limit(1);

  // 6. Business plan
  const [plan] = await db.select().from(artistBusinessPlans)
    .where(eq(artistBusinessPlans.artistId, artistId)).limit(1);

  // Social links check
  const hasSpotify = !!artist.spotifyUrl;
  const hasInstagram = !!artist.instagramHandle;
  const hasTwitter = !!artist.twitterHandle;
  const hasYoutube = !!artist.youtubeChannel;
  const hasTikTok = !!artist.tiktokUrl;
  const hasFacebook = !!artist.facebookUrl;
  const socialLinksCount = [hasSpotify, hasInstagram, hasTwitter, hasYoutube, hasTikTok, hasFacebook]
    .filter(Boolean).length;

  const vaultTotal = vault
    ? Number(vault.operationBalance || 0) + Number(vault.reserveBalance || 0) +
      Number(vault.growthBalance || 0) + Number(vault.defiBalance || 0)
    : 0;

  // Profile completeness score
  let completeness = 0;
  if (artist.artistName || artist.firstName) completeness += 10;
  if (artist.biography && artist.biography.length > 50) completeness += 10;
  if (artist.profileImage) completeness += 10;
  if (artist.coverImage) completeness += 5;
  if (artist.genre || (artist.genres as string[])?.length) completeness += 5;
  if (artist.country) completeness += 5;
  if (socialLinksCount >= 1) completeness += 5;
  if (socialLinksCount >= 3) completeness += 10;
  if (Number(songCount?.count) >= 1) completeness += 10;
  if (Number(songCount?.count) >= 5) completeness += 5;
  if (Number(merchCount?.count) >= 1) completeness += 5;
  if (Number(tokenCount?.count) >= 1) completeness += 10;
  if (profile?.isEnabled) completeness += 5;
  if (plan) completeness += 5;

  return {
    artistId,
    artistName: artist.artistName || artist.firstName || artist.username || 'Artist',
    slug: artist.slug || String(artistId),
    genre: artist.genre || (artist.genres as string[] || []).join(', ') || '',
    biography: artist.biography || '',
    country: artist.country || undefined,
    profileImage: artist.profileImage || undefined,
    totalSongs: Number(songCount?.count || 0),
    totalMerch: Number(merchCount?.count || 0),
    totalTokens: Number(tokenCount?.count || 0),
    hasSpotify,
    hasInstagram,
    hasTwitter,
    hasYoutube,
    hasTikTok,
    hasFacebook,
    socialLinksCount,
    engineEnabled: !!profile?.isEnabled,
    engineMode: profile?.operatingMode || 'none',
    vaultTotal,
    vaultOperation: Number(vault?.operationBalance || 0),
    vaultReserve: Number(vault?.reserveBalance || 0),
    vaultGrowth: Number(vault?.growthBalance || 0),
    vaultDefi: Number(vault?.defiBalance || 0),
    profileCompleteness: Math.min(completeness, 100),
    hasBiography: !!(artist.biography && artist.biography.length > 30),
    hasBusinessPlan: !!plan,
    hasPitchDeck: !!(plan?.pitchDeckData),
    hasExecutiveSummary: !!(plan?.executiveSummary),
    scannedAt: new Date().toISOString(),
  };
}

// ═══════════════════════════════════════════
// SMART MILESTONE GENERATOR — Based on profile gaps
// ═══════════════════════════════════════════

function generateSmartMilestones(snapshot: ProfileSnapshot, existing: RoadmapMilestone[]): RoadmapMilestone[] {
  const newMilestones: RoadmapMilestone[] = [];
  const existingIds = new Set(existing.map(m => m.id));
  const now = new Date();
  const addMonths = (m: number) => {
    const d = new Date(now);
    d.setMonth(d.getMonth() + m);
    return d.toISOString().split('T')[0];
  };

  // Helper: only create if not already exists
  const add = (m: RoadmapMilestone) => {
    if (!existingIds.has(m.id)) newMilestones.push(m);
  };

  // ── PHASE 1: Profile Foundations ──

  if (!snapshot.hasBiography) {
    add({
      id: 'smart-biography',
      title: 'Complete artist biography',
      date: addMonths(0),
      category: 'growth',
      status: 'planned',
      description: 'Write a compelling biography (50+ words) for your profile',
      autoGenerated: true,
      priority: 'high',
      profileMetric: 'hasBiography',
      targetValue: 1,
      currentValue: 0,
      action: { type: 'publish_news', payload: { template: 'profile_complete' } },
    });
  }

  if (snapshot.socialLinksCount < 3) {
    add({
      id: 'smart-social-links',
      title: `Connect ${3 - snapshot.socialLinksCount} more social accounts`,
      date: addMonths(0),
      category: 'growth',
      status: snapshot.socialLinksCount >= 1 ? 'in_progress' : 'planned',
      description: 'Link Spotify, Instagram, Twitter, YouTube, TikTok to your profile',
      autoGenerated: true,
      priority: 'high',
      profileMetric: 'socialLinksCount',
      targetValue: 3,
      currentValue: snapshot.socialLinksCount,
    });
  }

  if (!snapshot.profileImage) {
    add({
      id: 'smart-profile-image',
      title: 'Upload profile image',
      date: addMonths(0),
      category: 'branding',
      status: 'planned',
      description: 'Add a professional profile image',
      autoGenerated: true,
      priority: 'high',
      profileMetric: 'profileImage',
      targetValue: 1,
      currentValue: 0,
    });
  }

  // ── PHASE 2: Music Catalog ──

  const songTargets = [1, 3, 5, 10, 20, 50];
  for (const target of songTargets) {
    if (snapshot.totalSongs < target) {
      add({
        id: `smart-songs-${target}`,
        title: `Release ${target} song${target > 1 ? 's' : ''} total`,
        date: addMonths(target <= 3 ? 1 : target <= 10 ? 3 : 6),
        category: 'release',
        status: snapshot.totalSongs >= target * 0.5 ? 'in_progress' : 'planned',
        description: `Build your catalog to ${target} published songs`,
        autoGenerated: true,
        priority: target <= 3 ? 'critical' : target <= 10 ? 'high' : 'medium',
        profileMetric: 'totalSongs',
        targetValue: target,
        currentValue: snapshot.totalSongs,
        action: { type: 'publish_news', payload: { template: 'catalog_milestone', target } },
      });
      break; // Only add the next reachable target
    }
  }

  // ── PHASE 3: Monetization ──

  if (snapshot.totalMerch === 0) {
    add({
      id: 'smart-merch-launch',
      title: 'Launch merchandise store',
      date: addMonths(2),
      category: 'revenue',
      status: 'planned',
      description: 'Create and publish your first merchandise product',
      autoGenerated: true,
      priority: 'medium',
      profileMetric: 'totalMerch',
      targetValue: 1,
      currentValue: 0,
      action: { type: 'publish_news', payload: { template: 'merch_launched' } },
    });
  }

  if (snapshot.totalTokens === 0 && snapshot.totalSongs >= 1) {
    add({
      id: 'smart-tokenize',
      title: 'Tokenize your first song',
      date: addMonths(2),
      category: 'financial',
      status: 'planned',
      description: 'Create a music token on the blockchain to enable fan investment',
      autoGenerated: true,
      priority: 'high',
      profileMetric: 'totalTokens',
      targetValue: 1,
      currentValue: 0,
      action: { type: 'publish_news', payload: { template: 'song_tokenized' } },
    });
  }

  // ── PHASE 4: Economic Engine ──

  if (!snapshot.engineEnabled) {
    add({
      id: 'smart-engine-activate',
      title: 'Activate Economic Engine',
      date: addMonths(1),
      category: 'engine',
      status: 'planned',
      description: 'Enable the autonomous economic engine to manage your treasury',
      autoGenerated: true,
      linkedToEngine: true,
      priority: 'critical',
      profileMetric: 'engineEnabled',
      targetValue: 1,
      currentValue: 0,
      action: { type: 'publish_news', payload: { template: 'engine_activated' } },
    });
  } else {
    // Engine mode upgrades
    const modeOrder = ['survival', 'stable', 'expansion', 'aggressive'];
    const currentIdx = modeOrder.indexOf(snapshot.engineMode);
    if (currentIdx >= 0 && currentIdx < modeOrder.length - 1) {
      const nextMode = modeOrder[currentIdx + 1];
      add({
        id: `smart-engine-${nextMode}`,
        title: `Upgrade engine to ${nextMode} mode`,
        date: addMonths(3),
        category: 'engine',
        status: 'planned',
        description: `Transition from ${snapshot.engineMode} to ${nextMode} for accelerated growth`,
        autoGenerated: true,
        linkedToEngine: true,
        priority: 'high',
        profileMetric: 'engineMode',
        action: { type: 'publish_news', payload: { template: 'engine_upgrade', oldMode: snapshot.engineMode, newMode: nextMode } },
      });
    }
  }

  // ── PHASE 5: Treasury Vault ──

  const vaultTargets = [100, 500, 1000, 5000, 10000, 50000];
  for (const target of vaultTargets) {
    if (snapshot.vaultTotal < target) {
      add({
        id: `smart-vault-${target}`,
        title: `Reach $${target.toLocaleString()} in treasury vault`,
        date: addMonths(target <= 500 ? 2 : target <= 5000 ? 6 : 12),
        category: 'financial',
        status: snapshot.vaultTotal >= target * 0.5 ? 'in_progress' : 'planned',
        description: `Accumulate $${target.toLocaleString()} across all vault buckets`,
        autoGenerated: true,
        linkedToEngine: true,
        priority: target <= 1000 ? 'high' : 'medium',
        profileMetric: 'vaultTotal',
        targetValue: target,
        currentValue: snapshot.vaultTotal,
        action: { type: 'publish_news', payload: { template: 'vault_milestone', target } },
      });
      break; // Next reachable only
    }
  }

  // ── PHASE 6: Business & Pitch ──

  if (!snapshot.hasBusinessPlan) {
    add({
      id: 'smart-business-plan',
      title: 'Create Business Plan',
      date: addMonths(1),
      category: 'growth',
      status: 'planned',
      description: 'Set up revenue streams, expenses, and financial goals',
      autoGenerated: true,
      priority: 'high',
      profileMetric: 'hasBusinessPlan',
      targetValue: 1,
      currentValue: 0,
    });
  }

  if (snapshot.hasBusinessPlan && !snapshot.hasPitchDeck) {
    add({
      id: 'smart-pitch-deck',
      title: 'Generate Investor Pitch Deck',
      date: addMonths(2),
      category: 'growth',
      status: 'planned',
      description: 'Use AI to create a professional investor pitch deck',
      autoGenerated: true,
      priority: 'medium',
      profileMetric: 'hasPitchDeck',
      targetValue: 1,
      currentValue: 0,
    });
  }

  // ── PHASE 7: Profile completeness ──

  if (snapshot.profileCompleteness < 80) {
    add({
      id: 'smart-profile-80',
      title: 'Reach 80% profile completeness',
      date: addMonths(1),
      category: 'growth',
      status: snapshot.profileCompleteness >= 50 ? 'in_progress' : 'planned',
      description: `Currently at ${snapshot.profileCompleteness}% — complete all profile sections`,
      autoGenerated: true,
      priority: 'high',
      profileMetric: 'profileCompleteness',
      targetValue: 80,
      currentValue: snapshot.profileCompleteness,
      action: { type: 'publish_news', payload: { template: 'profile_milestone' } },
    });
  }

  return newMilestones;
}

// ═══════════════════════════════════════════
// MILESTONE EVALUATOR — Check which milestones should complete
// ═══════════════════════════════════════════

function evaluateMilestone(m: RoadmapMilestone, snapshot: ProfileSnapshot): 'completed' | 'in_progress' | null {
  if (m.status === 'completed') return null;

  // If the milestone has a specific profile metric, check it
  if (m.profileMetric && m.targetValue !== undefined) {
    const current = getMetricValue(m.profileMetric, snapshot);
    if (current >= m.targetValue) return 'completed';
    if (current >= m.targetValue * 0.5 && m.status === 'planned') return 'in_progress';
    return null;
  }

  // Fallback: title-based detection for manual milestones
  const title = m.title.toLowerCase();

  // Song count milestones
  const songMatch = title.match(/(\d+)\s*song/);
  if (songMatch && snapshot.totalSongs >= parseInt(songMatch[1])) return 'completed';

  // Vault milestones
  const vaultMatch = title.match(/\$?([\d,]+)\s*(in\s+)?(treasury|vault)/);
  if (vaultMatch && snapshot.vaultTotal >= parseInt(vaultMatch[1].replace(/,/g, ''))) return 'completed';

  // Engine mode milestones
  if (title.includes('economic engine') || title.includes('activate engine')) {
    if (snapshot.engineEnabled) return 'completed';
  }
  const modeMatch = title.match(/engine.*?(survival|stable|expansion|aggressive)/);
  if (modeMatch && snapshot.engineMode === modeMatch[1]) return 'completed';

  // Social links
  if (title.includes('social') && title.match(/\d/)) {
    const target = parseInt(title.match(/(\d+)/)?.[1] || '3');
    if (snapshot.socialLinksCount >= target) return 'completed';
  }

  // Merch
  if (title.includes('merch') && snapshot.totalMerch > 0) return 'completed';

  // Tokenize
  if (title.includes('tokeniz') && snapshot.totalTokens > 0) return 'completed';

  // Biography
  if (title.includes('biograph') && snapshot.hasBiography) return 'completed';

  return null;
}

function getMetricValue(metric: string, snapshot: ProfileSnapshot): number {
  const map: Record<string, number> = {
    totalSongs: snapshot.totalSongs,
    totalMerch: snapshot.totalMerch,
    totalTokens: snapshot.totalTokens,
    socialLinksCount: snapshot.socialLinksCount,
    vaultTotal: snapshot.vaultTotal,
    engineEnabled: snapshot.engineEnabled ? 1 : 0,
    profileCompleteness: snapshot.profileCompleteness,
    hasBiography: snapshot.hasBiography ? 1 : 0,
    hasBusinessPlan: snapshot.hasBusinessPlan ? 1 : 0,
    hasPitchDeck: snapshot.hasPitchDeck ? 1 : 0,
    hasExecutiveSummary: snapshot.hasExecutiveSummary ? 1 : 0,
    profileImage: snapshot.profileImage ? 1 : 0,
  };
  return map[metric] ?? 0;
}

// ═══════════════════════════════════════════
// ACTION EXECUTOR — Run actions when milestones complete
// ═══════════════════════════════════════════

async function executeMilestoneAction(
  milestone: RoadmapMilestone,
  snapshot: ProfileSnapshot,
): Promise<string | null> {
  const action = milestone.action;
  if (!action) return null;

  try {
    switch (action.type) {
      case 'publish_news':
        await publishMilestoneNews(milestone, snapshot, action.payload || {});
        return `Published news: "${milestone.title}"`;

      case 'generate_content':
        // Could trigger AI content generation for social posts
        return `Content generated for: "${milestone.title}"`;

      case 'send_notification':
        // Future: push notification to artist
        return `Notification sent for: "${milestone.title}"`;

      case 'trigger_campaign':
        // Future: auto-start outreach campaign
        return `Campaign triggered for: "${milestone.title}"`;

      default:
        return null;
    }
  } catch (e: any) {
    console.error(`[RoadmapEngine] Action execution failed for "${milestone.title}":`, e.message);
    return null;
  }
}

// ═══════════════════════════════════════════
// NEWS PUBLISHER — Generate and publish news from milestones
// ═══════════════════════════════════════════

async function publishMilestoneNews(
  milestone: RoadmapMilestone,
  snapshot: ProfileSnapshot,
  payload: Record<string, any>,
): Promise<void> {
  const template = payload.template || 'milestone_reached';

  // Build a rich news event
  const eventPayload: NewsEventPayload = {
    type: 'milestone_reached',
    artistId: snapshot.artistId,
    artistName: snapshot.artistName,
    artistBio: snapshot.biography || undefined,
    genre: snapshot.genre || undefined,
    details: {
      milestoneTitle: milestone.title,
      milestoneCategory: milestone.category,
      milestoneDescription: milestone.description || milestone.title,
      priority: milestone.priority || 'medium',
      template,
      profileCompleteness: snapshot.profileCompleteness,
      totalSongs: snapshot.totalSongs,
      totalTokens: snapshot.totalTokens,
      vaultTotal: snapshot.vaultTotal,
      engineMode: snapshot.engineMode,
      ...payload,
    },
  };

  // Specific event types for better article quality
  if (template === 'song_tokenized') {
    eventPayload.type = 'song_tokenized';
  } else if (template === 'merch_launched') {
    eventPayload.type = 'merch_launched';
  } else if (template === 'engine_activated' || template === 'engine_upgrade') {
    eventPayload.details!.milestoneTitle = milestone.title;
    eventPayload.details!.milestoneDescription =
      `${snapshot.artistName}'s economic engine milestone: ${milestone.title}. ` +
      `Current mode: ${snapshot.engineMode}, vault balance: $${snapshot.vaultTotal.toFixed(2)}.`;
  } else if (template === 'catalog_milestone') {
    eventPayload.details!.milestoneDescription =
      `${snapshot.artistName} reached ${snapshot.totalSongs} songs in their catalog. ` +
      `A growing ${snapshot.genre || 'music'} catalog that shows consistent artistic output.`;
  } else if (template === 'vault_milestone') {
    eventPayload.details!.milestoneDescription =
      `${snapshot.artistName}'s treasury vault crossed $${(payload.target || snapshot.vaultTotal).toLocaleString()}. ` +
      `Operating in ${snapshot.engineMode} mode with autonomous financial management.`;
  }

  enqueueNewsEvent(eventPayload);
  console.log(`📰 [RoadmapEngine] News enqueued: "${milestone.title}" for ${snapshot.artistName}`);
}

// ═══════════════════════════════════════════
// AI ROADMAP ADVISOR — Generate recommendations
// ═══════════════════════════════════════════

export async function generateRoadmapAdvice(snapshot: ProfileSnapshot): Promise<string> {
  try {
    const response = await openai.chat.completions.create({
      model: PRIMARY_MODEL,
      messages: [
        {
          role: 'system',
          content: `You are a professional music industry business strategist. Analyze the artist's current profile state and give 3-5 specific, actionable next steps for their roadmap. Be concise (max 200 words). Focus on what's missing and what would have the highest impact. Use bullet points.`,
        },
        {
          role: 'user',
          content: `Artist: ${snapshot.artistName}
Genre: ${snapshot.genre || 'Not set'}
Songs: ${snapshot.totalSongs}
Merch products: ${snapshot.totalMerch}
Tokenized songs: ${snapshot.totalTokens}
Social links connected: ${snapshot.socialLinksCount}/6 (${[
  snapshot.hasSpotify ? 'Spotify' : null,
  snapshot.hasInstagram ? 'Instagram' : null,
  snapshot.hasTwitter ? 'Twitter' : null,
  snapshot.hasYoutube ? 'YouTube' : null,
  snapshot.hasTikTok ? 'TikTok' : null,
  snapshot.hasFacebook ? 'Facebook' : null,
].filter(Boolean).join(', ') || 'None'})
Economic Engine: ${snapshot.engineEnabled ? snapshot.engineMode + ' mode' : 'Not activated'}
Treasury Vault: $${snapshot.vaultTotal.toFixed(2)}
Profile completeness: ${snapshot.profileCompleteness}%
Has biography: ${snapshot.hasBiography}
Has business plan: ${snapshot.hasBusinessPlan}
Has pitch deck: ${snapshot.hasPitchDeck}

What are the most impactful next steps for this artist's career roadmap?`,
        },
      ],
      max_tokens: 400,
      temperature: 0.7,
    });

    return response.choices[0]?.message?.content?.trim() || 'Focus on releasing more music and connecting your social accounts.';
  } catch (e: any) {
    console.error('[RoadmapEngine] AI advice failed:', e.message);
    return 'Focus on: 1) Upload more songs, 2) Connect social accounts, 3) Activate the economic engine, 4) Create merchandise, 5) Tokenize your music.';
  }
}

// ═══════════════════════════════════════════
// MAIN: Full Roadmap Scan & Update
// ═══════════════════════════════════════════

export async function runRoadmapScan(artistId: number): Promise<RoadmapScanResult> {
  console.log(`🔍 [RoadmapEngine] Running full scan for artist ${artistId}...`);

  // 1. Scan current profile state
  const snapshot = await scanArtistProfile(artistId);

  // 2. Get or create business plan
  let [plan] = await db.select().from(artistBusinessPlans)
    .where(eq(artistBusinessPlans.artistId, artistId)).limit(1);

  if (!plan) {
    [plan] = await db.insert(artistBusinessPlans).values({
      artistId,
      businessName: `${snapshot.artistName} Music`,
      roadmapAutoUpdate: true,
      milestones: [],
      roadmapExecutionLog: [],
    }).returning();
  }

  const milestones: RoadmapMilestone[] = (plan.milestones as RoadmapMilestone[]) || [];
  const executionLog: any[] = (plan.roadmapExecutionLog as any[]) || [];
  const result: RoadmapScanResult = {
    snapshot,
    milestonesUpdated: [],
    milestonesCreated: [],
    actionsExecuted: [],
    newsGenerated: [],
  };
  const now = new Date();

  // 3. Generate smart milestones based on profile gaps
  const newMilestones = generateSmartMilestones(snapshot, milestones);
  for (const m of newMilestones) {
    milestones.push(m);
    result.milestonesCreated.push(m.title);
  }

  // 4. Evaluate all milestones against current profile
  for (let i = 0; i < milestones.length; i++) {
    const m = milestones[i];
    if (m.status === 'completed') continue;

    // Update currentValue for tracking
    if (m.profileMetric) {
      milestones[i].currentValue = getMetricValue(m.profileMetric, snapshot);
    }

    const evaluation = evaluateMilestone(m, snapshot);

    if (evaluation === 'completed') {
      milestones[i] = {
        ...milestones[i],
        status: 'completed',
        completedAt: now.toISOString(),
      };
      result.milestonesUpdated.push(m.title);

      executionLog.push({
        milestoneId: m.id,
        event: 'auto_completed',
        plannedDate: m.date,
        actualDate: now.toISOString(),
        details: `"${m.title}" completed — profile scan detected target met`,
        timestamp: now.toISOString(),
      });

      // 5. Execute milestone action
      if (m.action && !m.newsPublished) {
        const actionResult = await executeMilestoneAction(m, snapshot);
        if (actionResult) {
          result.actionsExecuted.push(actionResult);
          milestones[i].action = { ...m.action, executedAt: now.toISOString(), result: actionResult };
          milestones[i].newsPublished = true;
          result.newsGenerated.push(m.title);
        }
      }

    } else if (evaluation === 'in_progress' && m.status === 'planned') {
      milestones[i] = { ...milestones[i], status: 'in_progress' };
      result.milestonesUpdated.push(`${m.title} (started)`);

      executionLog.push({
        milestoneId: m.id,
        event: 'auto_started',
        plannedDate: m.date,
        details: `"${m.title}" — progress detected`,
        timestamp: now.toISOString(),
      });
    }
  }

  // 6. Save everything
  await db.update(artistBusinessPlans).set({
    milestones,
    roadmapExecutionLog: executionLog.slice(-200),
    lastRoadmapSync: now,
    updatedAt: now,
  }).where(eq(artistBusinessPlans.artistId, artistId));

  console.log(
    `✅ [RoadmapEngine] Scan complete: ${result.milestonesCreated.length} created, ` +
    `${result.milestonesUpdated.length} updated, ${result.actionsExecuted.length} actions, ` +
    `${result.newsGenerated.length} news`
  );

  return result;
}

// ═══════════════════════════════════════════
// PERIODIC SCANNER — For all artists with auto-update enabled
// ═══════════════════════════════════════════

export async function runGlobalRoadmapScan(): Promise<{ scanned: number; updated: number }> {
  const plans = await db.select({ artistId: artistBusinessPlans.artistId })
    .from(artistBusinessPlans)
    .where(eq(artistBusinessPlans.roadmapAutoUpdate, true));

  let updated = 0;
  for (const { artistId } of plans) {
    try {
      const result = await runRoadmapScan(artistId);
      if (result.milestonesUpdated.length > 0 || result.milestonesCreated.length > 0) updated++;
    } catch (e: any) {
      console.error(`[RoadmapEngine] Global scan failed for artist ${artistId}:`, e.message);
    }
  }

  console.log(`[RoadmapEngine] Global scan: ${plans.length} scanned, ${updated} updated`);
  return { scanned: plans.length, updated };
}
