#!/bin/bash
# ==============================================================
#  HERMES AGENT — BOOSTIFY SETUP SCRIPT FOR WSL2
# ==============================================================
#
# Run this inside WSL2 (not Windows PowerShell).
# Prerequisites: WSL2 with Ubuntu installed
#
# Usage:
#   wsl -e bash hermes/setup-hermes-wsl2.sh
#
# Or inside WSL2:
#   chmod +x hermes/setup-hermes-wsl2.sh
#   ./hermes/setup-hermes-wsl2.sh

set -e

echo "🚀 Installing Hermes Agent for Boostify..."
echo "============================================"

# ─── Step 1: Install Hermes ───────────────────────────────────
echo ""
echo "📦 [1/5] Installing Hermes Agent..."
curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash

# Reload shell paths
export PATH="$HOME/.local/bin:$PATH"
source ~/.bashrc 2>/dev/null || true

echo "✅ Hermes installed"

# ─── Step 2: Configure API Keys ───────────────────────────────
echo ""
echo "🔑 [2/5] Configuring API keys..."

# Read keys from Windows-side .env (mounted at /mnt/c/)
BOOSTIFY_DIR="/mnt/c/Users/convo/OneDrive/Escritorio/BOOSTIFY 2025/BOOSTIFY-MUSIC_LAST/BOOSTIFY-MUSIC"
ENV_FILE="$BOOSTIFY_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    OPENROUTER_KEY=$(grep "^OPENROUTER_API_KEY=" "$ENV_FILE" | cut -d'=' -f2)
    OPENAI_KEY=$(grep "^OPENAI_API_KEY=" "$ENV_FILE" | cut -d'=' -f2)
    echo "✅ Found API keys from Boostify .env"
else
    echo "⚠️  Could not find Boostify .env. Enter keys manually."
    read -p "OpenRouter API Key (or press Enter to skip): " OPENROUTER_KEY
    read -p "OpenAI API Key (or press Enter to skip): " OPENAI_KEY
fi

# ─── Step 3: Create Hermes config ──────────────────────────────
echo ""
echo "⚙️  [3/5] Creating Hermes configuration..."

mkdir -p ~/.hermes

cat > ~/.hermes/.env << EOF
# Boostify Hermes Agent Configuration
# Generated by setup-hermes-wsl2.sh on $(date)

# AI Provider
OPENROUTER_API_KEY=${OPENROUTER_KEY}
OPENAI_API_KEY=${OPENAI_KEY}
HERMES_DEFAULT_PROVIDER=openrouter
HERMES_DEFAULT_MODEL=anthropic/claude-3.5-sonnet

# Boostify Integration
BOOSTIFY_API_URL=http://localhost:3000
HERMES_API_SECRET=boostify-hermes-secret-2026
BOOSTIFY_ARTIST_ID=

# Hermes Settings
HERMES_HOME=~/.hermes
EOF

echo "✅ Hermes config created at ~/.hermes/.env"

# ─── Step 4: Install Boostify custom tools ─────────────────────
echo ""
echo "🔧 [4/5] Installing Boostify custom tools..."

mkdir -p ~/.hermes/skills/boostify-tools

# Copy tools from Windows-side
if [ -f "$BOOSTIFY_DIR/hermes/skills/boostify_tools.py" ]; then
    cp "$BOOSTIFY_DIR/hermes/skills/boostify_tools.py" ~/.hermes/skills/boostify-tools/
    echo "✅ boostify_tools.py copied"
fi

# Copy skills
for skill in artist_weekly_check.md content_calendar.md competitor_analysis.md; do
    if [ -f "$BOOSTIFY_DIR/hermes/skills/$skill" ]; then
        cp "$BOOSTIFY_DIR/hermes/skills/$skill" ~/.hermes/skills/
        echo "✅ Skill: $skill"
    fi
done

# Copy AGENTS.md (workspace context)
if [ -f "$BOOSTIFY_DIR/hermes/AGENTS.md" ]; then
    cp "$BOOSTIFY_DIR/hermes/AGENTS.md" ~/.hermes/AGENTS.md
    echo "✅ AGENTS.md (workspace context)"
fi

# Create profiles directory
mkdir -p ~/.hermes/profiles

# ─── Step 5: Verify installation ──────────────────────────────
echo ""
echo "✅ [5/5] Verifying installation..."

if command -v hermes &> /dev/null; then
    echo "✅ Hermes command found: $(hermes --version 2>/dev/null || echo 'installed')"
else
    echo "⚠️  hermes command not in PATH. Try: source ~/.bashrc"
fi

echo ""
echo "============================================"
echo "🎉 HERMES AGENT SETUP COMPLETE!"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Set your artist ID:"
echo "     hermes config set BOOSTIFY_ARTIST_ID=1391"
echo ""
echo "  2. Test Boostify connection:"
echo "     cd ~/.hermes/skills/boostify-tools && python boostify_tools.py"
echo ""
echo "  3. Start Hermes:"
echo "     hermes"
echo ""
echo "  4. In Hermes, try:"
echo "     'Load my Boostify artist profile and tell me my goals'"
echo ""
echo "  5. Set up cron for weekly artist check:"
echo "     hermes cron add '0 9 * * 1' 'Run the artist_weekly_check skill'"
echo ""
echo "  Optional - Start Telegram gateway:"
echo "     hermes gateway setup  # Follow prompts for Telegram bot token"
echo "     hermes gateway start"
echo ""
echo "🎵 Boostify API runs at: http://localhost:3000/api/hermes/status"
echo ""
