/**
 * Asset CDN Middleware
 *
 * Intercepts requests for media files (videos/audio/PDFs) and redirects them
 * to their Firebase Storage CDN URLs.
 *
 * - Local dev: Vite serves files from client/public BEFORE Express runs,
 *   so this middleware is a no-op when files exist locally.
 * - Production: Express serves the built app. Files NOT included in the build
 *   (videos, audio) are redirected here to their Firebase Storage URLs.
 *
 * The map is generated by `scripts/upload-app-assets-to-firebase.ts`.
 */
import type { Request, Response, NextFunction } from 'express';
import fs from 'node:fs';
import path from 'node:path';

let assetMap: Record<string, string> = {};
const MAP_PATH = path.resolve(process.cwd(), 'server', 'asset-cdn-map.json');

try {
  if (fs.existsSync(MAP_PATH)) {
    assetMap = JSON.parse(fs.readFileSync(MAP_PATH, 'utf-8'));
    console.log(`📡 Asset CDN map loaded: ${Object.keys(assetMap).length} entries`);
  } else {
    console.log('ℹ️  No asset-cdn-map.json found — CDN redirects disabled');
  }
} catch (err) {
  console.error('⚠️ Could not load asset-cdn-map.json:', err);
}

export function assetCdnMiddleware(req: Request, res: Response, next: NextFunction) {
  // Only handle GET/HEAD
  if (req.method !== 'GET' && req.method !== 'HEAD') return next();

  // Try exact match first
  const cdnUrl = assetMap[req.path];
  if (cdnUrl) {
    // 302 to allow updates without cache invalidation; CDN handles long-term caching
    return res.redirect(302, cdnUrl);
  }

  next();
}

/**
 * Get the CDN URL for a public asset path, or fallback to the original path.
 * Useful for server-side rendering and shared between client/server.
 */
export function getAssetUrl(publicPath: string): string {
  return assetMap[publicPath] || publicPath;
}
