import { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Facebook, ChevronDown, Plus, Trash2, Sparkles, Send, Copy, ExternalLink,
  CheckCircle2, Clock, Settings as SettingsIcon, Layers, Users, Rocket,
  ShieldAlert, RefreshCw, Calendar, Music, ShoppingBag, Image as ImageIcon,
  Megaphone, X, Power, SkipForward, Search, Compass, Flame, Youtube,
} from 'lucide-react';
import { apiRequest } from '../../../lib/queryClient';

interface Props {
  artistId: string;
  artistName: string;
  artistImageUrl?: string | null;
}

type ContentType = 'song' | 'merch' | 'social_post' | 'concert' | 'photo' | 'lyric_video' | 'custom';

interface FbGroup {
  id: string; name: string; url?: string | null; memberCount?: number | null;
  category?: string | null; notes?: string | null; active?: boolean;
  publishCount?: number; lastPublishedAt?: number | null;
}
interface PromotableItem {
  contentType: ContentType; contentId: string; title: string;
  subtitle?: string | null; imageUrl?: string | null; link?: string | null;
}
interface QueueItem {
  id: string; contentType: ContentType; contentId?: string | null; title: string;
  subtitle?: string | null; imageUrl?: string | null; link?: string | null;
  caption: string; groupIds: string[]; publishedGroups?: Record<string, number>;
  status: 'ready' | 'scheduled' | 'published' | 'skipped' | 'draft';
  scheduledAt: number; autoGenerated?: boolean; createdAt: number;
}
interface FbSettings {
  autopilot: boolean; hybridMode: boolean; dailyCap: number; minIntervalMinutes: number;
  rotateContent: boolean; tone: string; language: string; defaultGroupIds: string[];
}
type SizeTier = 'mega' | 'large' | 'mid' | 'niche';
interface DiscoveredGroup {
  name: string; query: string; searchUrl: string; niche: string;
  sizeTier: SizeTier; estMembers: string; relevance: string; language?: string;
}

const TYPE_META: Record<string, { label: string; icon: any; color: string }> = {
  song: { label: 'Song', icon: Music, color: '#a855f7' },
  merch: { label: 'Merch', icon: ShoppingBag, color: '#f59e0b' },
  social_post: { label: 'Post', icon: Megaphone, color: '#ec4899' },
  concert: { label: 'Concert', icon: Calendar, color: '#10b981' },
  photo: { label: 'Photo', icon: ImageIcon, color: '#38bdf8' },
  lyric_video: { label: 'Lyric Video', icon: Youtube, color: '#ef4444' },
  custom: { label: 'Custom', icon: Layers, color: '#94a3b8' },
};

const TABS = [
  { key: 'overview', label: 'Overview', icon: Rocket },
  { key: 'discover', label: 'Discover', icon: Compass },
  { key: 'groups', label: 'Groups', icon: Users },
  { key: 'content', label: 'Content', icon: Layers },
  { key: 'queue', label: 'Queue / Publish', icon: Send },
  { key: 'settings', label: 'Settings', icon: SettingsIcon },
] as const;
type TabKey = (typeof TABS)[number]['key'];

const BLUE = '#1877F2';

const TIER_META: Record<SizeTier, { label: string; range: string; color: string; icon: any }> = {
  mega: { label: 'Mega', range: '500k+', color: '#f43f5e', icon: Flame },
  large: { label: 'Large', range: '50k–500k', color: '#f59e0b', icon: Users },
  mid: { label: 'Mid', range: '5k–50k', color: '#38bdf8', icon: Users },
  niche: { label: 'Niche', range: '<5k', color: '#a855f7', icon: Users },
};
const TIER_ORDER: SizeTier[] = ['mega', 'large', 'mid', 'niche'];

/**
 * Facebook Groups Auto-Publishing Command Center — a CONTROLLED engine to share
 * the artist's content (songs, merch, posts, concerts, photos) into OPEN
 * Facebook groups. Hybrid mode: the engine prepares the queue with AI captions
 * and the artist confirms each publish with one click. Owner-only.
 */
export function FacebookGroupsCommandCenter({ artistId, artistName, artistImageUrl }: Props) {
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<TabKey>('overview');
  const qc = useQueryClient();
  const base = `/api/facebook-groups/${artistId}`;
  const invalidate = () => {
    qc.invalidateQueries({ queryKey: ['fb-groups-overview', artistId] });
    qc.invalidateQueries({ queryKey: ['fb-groups-groups', artistId] });
    qc.invalidateQueries({ queryKey: ['fb-groups-queue', artistId] });
  };

  // ── Queries ────────────────────────────────────────────────────────────────
  const overviewQ = useQuery({
    queryKey: ['fb-groups-overview', artistId],
    queryFn: async () => (await apiRequest({ url: `${base}/overview`, method: 'GET' })) || {},
    enabled: open,
  });
  const groupsQ = useQuery({
    queryKey: ['fb-groups-groups', artistId],
    queryFn: async () => ((await apiRequest({ url: `${base}/groups`, method: 'GET' }))?.groups || []) as FbGroup[],
    enabled: open,
  });
  const contentQ = useQuery({
    queryKey: ['fb-groups-content', artistId],
    queryFn: async () => ((await apiRequest({ url: `${base}/content`, method: 'GET' }))?.items || []) as PromotableItem[],
    enabled: open && tab === 'content',
  });
  const queueQ = useQuery({
    queryKey: ['fb-groups-queue', artistId],
    queryFn: async () => ((await apiRequest({ url: `${base}/queue`, method: 'GET' }))?.items || []) as QueueItem[],
    enabled: open && (tab === 'queue' || tab === 'overview'),
  });

  const settings: FbSettings | undefined = overviewQ.data?.settings;
  const stats = overviewQ.data?.stats || {};
  const groups = groupsQ.data || [];
  const activeGroups = useMemo(() => groups.filter((g) => g.active !== false), [groups]);

  // ── Mutations ───────────────────────────────────────────────────────────────
  const addGroup = useMutation({
    mutationFn: (body: any) => apiRequest({ url: `${base}/groups`, method: 'POST', data: body }),
    onSuccess: invalidate,
  });
  const patchGroup = useMutation({
    mutationFn: ({ id, body }: { id: string; body: any }) =>
      apiRequest({ url: `${base}/groups/${id}`, method: 'PATCH', data: body }),
    onSuccess: invalidate,
  });
  const deleteGroup = useMutation({
    mutationFn: (id: string) => apiRequest({ url: `${base}/groups/${id}`, method: 'DELETE' }),
    onSuccess: invalidate,
  });
  const enqueue = useMutation({
    mutationFn: (body: any) => apiRequest({ url: `${base}/queue`, method: 'POST', data: body }),
    onSuccess: () => { invalidate(); setTab('queue'); },
  });
  const markPublished = useMutation({
    mutationFn: ({ itemId, groupId }: { itemId: string; groupId: string }) =>
      apiRequest({ url: `${base}/queue/${itemId}/mark-published`, method: 'POST', data: { groupId } }),
    onSuccess: invalidate,
  });
  const skipItem = useMutation({
    mutationFn: (itemId: string) => apiRequest({ url: `${base}/queue/${itemId}/skip`, method: 'POST', data: {} }),
    onSuccess: invalidate,
  });
  const deleteItem = useMutation({
    mutationFn: (itemId: string) => apiRequest({ url: `${base}/queue/${itemId}`, method: 'DELETE' }),
    onSuccess: invalidate,
  });
  const saveSettings = useMutation({
    mutationFn: (body: any) => apiRequest({ url: `${base}/settings`, method: 'POST', data: body }),
    onSuccess: invalidate,
  });
  const runAutopilot = useMutation({
    mutationFn: () => apiRequest({ url: `${base}/autopilot/run`, method: 'POST', data: {} }),
    onSuccess: () => { invalidate(); setTab('queue'); },
  });

  return (
    <section id="facebook-groups-command-center" className="scroll-mt-24">
      <div className="overflow-hidden rounded-3xl border border-blue-500/15 bg-gradient-to-b from-[#0b1422] to-[#070a0f] shadow-[0_20px_80px_rgba(24,119,242,0.10)]">
        {/* Header */}
        <button onClick={() => setOpen((v) => !v)} className="flex w-full items-center gap-3 p-5 text-left">
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-[#1877F2] to-[#0d5fc4] text-white shadow-[0_0_24px_rgba(24,119,242,0.45)]">
            <Facebook className="h-6 w-6" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2">
              <h2 className="truncate text-lg font-bold text-white">Facebook Groups Autopilot</h2>
              <span className="rounded-full border border-blue-400/30 bg-blue-400/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-blue-300">
                Controlled
              </span>
            </div>
            <div className="mt-0.5 flex items-center gap-2 text-xs text-white/55">
              <Users className="h-3.5 w-3.5" />
              {stats.activeGroups ?? groups.length ?? 0} groups · {stats.ready ?? 0} ready to publish
            </div>
          </div>
          <motion.div animate={{ rotate: open ? 180 : 0 }}>
            <ChevronDown className="h-5 w-5 text-white/50" />
          </motion.div>
        </button>

        <AnimatePresence initial={false}>
          {open && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="overflow-hidden"
            >
              {/* Tab bar */}
              <div className="flex gap-1.5 overflow-x-auto border-y border-white/5 px-3 py-2.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
                {TABS.map(({ key, label, icon: Icon }) => (
                  <button
                    key={key}
                    onClick={() => setTab(key)}
                    className={`flex shrink-0 items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-medium transition ${
                      tab === key ? 'bg-blue-500/15 text-blue-200' : 'text-white/55 hover:bg-white/5 hover:text-white'
                    }`}
                  >
                    <Icon className="h-4 w-4" /> {label}
                  </button>
                ))}
              </div>

              {/* Disclaimer */}
              <div className="flex items-start gap-2 border-b border-white/5 bg-amber-400/[0.04] px-5 py-2.5 text-[11px] text-amber-200/70">
                <ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                <span>
                  <strong>Hybrid mode (recommended)</strong>: the engine prepares and schedules everything with AI captions,
                  but <strong>you confirm each publish with one click</strong>. Respect each Facebook group's rules
                  — never spam. Fully unattended auto-posting is not supported, to keep your account safe.
                </span>
              </div>

              <div className="p-5">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={tab}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -8 }}
                    transition={{ duration: 0.2 }}
                  >
                    {tab === 'overview' && (
                      <OverviewTab
                        stats={stats}
                        settings={settings}
                        nextReady={overviewQ.data?.nextReady || []}
                        groups={groups}
                        onRunAutopilot={() => runAutopilot.mutate()}
                        running={runAutopilot.isPending}
                        onGoQueue={() => setTab('queue')}
                        onGoGroups={() => setTab('groups')}
                      />
                    )}
                    {tab === 'discover' && (
                      <DiscoverTab
                        base={base}
                        existingGroups={groups}
                        onAddGroup={(b) => addGroup.mutate(b)}
                        adding={addGroup.isPending}
                      />
                    )}
                    {tab === 'groups' && (
                      <GroupsTab
                        groups={groups}
                        loading={groupsQ.isLoading}
                        onAdd={(b) => addGroup.mutate(b)}
                        adding={addGroup.isPending}
                        onToggle={(id, active) => patchGroup.mutate({ id, body: { active } })}
                        onDelete={(id) => deleteGroup.mutate(id)}
                      />
                    )}
                    {tab === 'content' && (
                      <ContentTab
                        items={contentQ.data || []}
                        loading={contentQ.isLoading}
                        groups={activeGroups}
                        base={base}
                        onEnqueue={(b) => enqueue.mutate(b)}
                        enqueuing={enqueue.isPending}
                      />
                    )}
                    {tab === 'queue' && (
                      <QueueTab
                        items={queueQ.data || []}
                        loading={queueQ.isLoading}
                        groups={groups}
                        onPublish={(itemId, groupId) => markPublished.mutate({ itemId, groupId })}
                        onSkip={(id) => skipItem.mutate(id)}
                        onDelete={(id) => deleteItem.mutate(id)}
                      />
                    )}
                    {tab === 'settings' && (
                      <SettingsTab
                        settings={settings}
                        groups={groups}
                        onSave={(b) => saveSettings.mutate(b)}
                        saving={saveSettings.isPending}
                      />
                    )}
                  </motion.div>
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}

// ───────────────────────────── Overview ──────────────────────────────────────
function OverviewTab({ stats, settings, nextReady, groups, onRunAutopilot, running, onGoQueue, onGoGroups }: {
  stats: any; settings?: FbSettings; nextReady: QueueItem[]; groups: FbGroup[];
  onRunAutopilot: () => void; running: boolean; onGoQueue: () => void; onGoGroups: () => void;
}) {
  const tiles = [
    { label: 'Active groups', value: stats.activeGroups ?? 0, icon: Users, color: '#38bdf8' },
    { label: 'Ready to publish', value: stats.ready ?? 0, icon: Send, color: '#10b981' },
    { label: 'Scheduled', value: stats.scheduled ?? 0, icon: Clock, color: '#f59e0b' },
    { label: 'Published today', value: `${stats.publishedToday ?? 0}/${stats.dailyCap ?? 8}`, icon: CheckCircle2, color: '#a855f7' },
  ];
  return (
    <div className="space-y-5">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        {tiles.map((t) => (
          <div key={t.label} className="rounded-2xl border border-white/5 bg-white/[0.02] p-4">
            <t.icon className="h-5 w-5" style={{ color: t.color }} />
            <div className="mt-2 text-2xl font-bold text-white">{t.value}</div>
            <div className="text-[11px] text-white/50">{t.label}</div>
          </div>
        ))}
      </div>

      <div className="flex flex-col gap-3 rounded-2xl border border-blue-500/15 bg-blue-500/[0.04] p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-2 text-sm font-semibold text-white">
            <Sparkles className="h-4 w-4 text-blue-300" /> Prepare posts now
          </div>
          <p className="mt-1 text-xs text-white/55">
            Generate AI captions and build the queue from your content (songs, merch, concerts, photos…),
            respecting your daily limit of {settings?.dailyCap ?? 8}.
          </p>
        </div>
        <button
          onClick={onRunAutopilot}
          disabled={running || groups.filter((g) => g.active !== false).length === 0}
          className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#1877F2] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#0d5fc4] disabled:opacity-40"
        >
          {running ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Rocket className="h-4 w-4" />}
          {running ? 'Preparing…' : 'Prepare queue'}
        </button>
      </div>

      {groups.length === 0 && (
        <button onClick={onGoGroups} className="w-full rounded-2xl border border-dashed border-white/15 bg-white/[0.02] p-4 text-center text-sm text-white/60 transition hover:border-blue-400/40 hover:text-white">
          <Plus className="mx-auto mb-1 h-5 w-5" />
          Add your first Facebook groups to get started
        </button>
      )}

      {nextReady.length > 0 && (
        <div>
          <div className="mb-2 flex items-center justify-between">
            <h4 className="text-sm font-semibold text-white">Up next</h4>
            <button onClick={onGoQueue} className="text-xs text-blue-300 hover:underline">View queue →</button>
          </div>
          <div className="space-y-2">
            {nextReady.slice(0, 3).map((it) => {
              const meta = TYPE_META[it.contentType] || TYPE_META.custom;
              return (
                <div key={it.id} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[0.02] p-3">
                  {it.imageUrl ? (
                    <img src={it.imageUrl} alt="" className="h-10 w-10 shrink-0 rounded-lg object-cover" />
                  ) : (
                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg" style={{ background: `${meta.color}22` }}>
                      <meta.icon className="h-5 w-5" style={{ color: meta.color }} />
                    </div>
                  )}
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-sm text-white">{it.title}</div>
                    <div className="text-[11px] text-white/45">{meta.label}</div>
                  </div>
                  <button onClick={onGoQueue} className="rounded-lg bg-blue-500/15 px-3 py-1.5 text-xs font-medium text-blue-200">Publish</button>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

// ───────────────────────────── Discover ──────────────────────────────────────
function DiscoverTab({ base, existingGroups, onAddGroup, adding }: {
  base: string; existingGroups: FbGroup[]; onAddGroup: (b: any) => void; adding: boolean;
}) {
  const [keyword, setKeyword] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{
    keyword: string; genre?: string; keywords: string[]; groups: DiscoveredGroup[];
    byTier: Record<SizeTier, DiscoveredGroup[]>; note?: string;
  } | null>(null);
  const [added, setAdded] = useState<Record<string, boolean>>({});
  const [tierFilter, setTierFilter] = useState<SizeTier | 'all'>('all');

  const existingNames = useMemo(
    () => new Set(existingGroups.map((g) => g.name.toLowerCase().trim())),
    [existingGroups],
  );

  const run = async (kw?: string) => {
    const q = (kw ?? keyword).trim();
    if (!q) return;
    setKeyword(q);
    setLoading(true);
    try {
      const res = await apiRequest({ url: `${base}/discover`, method: 'POST', data: { keyword: q } });
      if (res?.success) {
        setResult({ keyword: res.keyword, genre: res.genre, keywords: res.keywords || [], groups: res.groups || [], byTier: res.byTier, note: res.note });
        setTierFilter('all');
      }
    } finally { setLoading(false); }
  };

  const add = (g: DiscoveredGroup) => {
    onAddGroup({ name: g.name, url: g.searchUrl, category: g.niche });
    setAdded((p) => ({ ...p, [g.name]: true }));
  };

  const shown = result
    ? (tierFilter === 'all' ? result.groups : result.groups.filter((g) => g.sizeTier === tierFilter))
    : [];

  return (
    <div className="space-y-4">
      {/* Search bar */}
      <div className="rounded-2xl border border-blue-500/15 bg-blue-500/[0.04] p-4">
        <div className="mb-1 flex items-center gap-2 text-sm font-semibold text-white">
          <Compass className="h-4 w-4 text-blue-300" /> Keyword group discoverer
        </div>
        <p className="mb-3 text-xs text-white/55">
          The AI knows your genre and suggests the best open groups, separated by size.
          Verify the real member count on Facebook and add them with one click.
        </p>
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/30" />
            <input
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && run()}
              placeholder="e.g. alternative rock, indie music, NYC concerts…"
              className="w-full rounded-xl border border-white/10 bg-black/30 pl-9 pr-3 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-blue-400/50"
            />
          </div>
          <button onClick={() => run()} disabled={loading || !keyword.trim()}
            className="flex shrink-0 items-center gap-2 rounded-xl bg-[#1877F2] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#0d5fc4] disabled:opacity-40">
            {loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            {loading ? 'Searching…' : 'Discover'}
          </button>
        </div>
      </div>

      {loading && !result && (
        <div className="py-8 text-center text-sm text-white/40">The AI is finding the best groups…</div>
      )}

      {result && (
        <>
          {/* Keyword variations */}
          {result.keywords.length > 0 && (
            <div>
              <div className="mb-1.5 text-[11px] font-medium uppercase tracking-wide text-white/40">Other suggested searches</div>
              <div className="flex flex-wrap gap-1.5">
                {result.keywords.map((k) => (
                  <button key={k} onClick={() => run(k)}
                    className="rounded-lg bg-white/5 px-2.5 py-1.5 text-xs text-white/60 transition hover:bg-blue-500/15 hover:text-blue-200">
                    {k}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Tier filter */}
          <div className="flex flex-wrap gap-1.5">
            <FilterChip active={tierFilter === 'all'} onClick={() => setTierFilter('all')} label={`All (${result.groups.length})`} />
            {TIER_ORDER.map((t) => {
              const n = result.byTier?.[t]?.length || result.groups.filter((g) => g.sizeTier === t).length;
              if (!n) return null;
              const m = TIER_META[t];
              return (
                <button key={t} onClick={() => setTierFilter(t)}
                  className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition ${tierFilter === t ? 'text-white' : 'text-white/50 hover:text-white'}`}
                  style={tierFilter === t ? { background: `${m.color}33`, boxShadow: `inset 0 0 0 1px ${m.color}66` } : { background: 'rgba(255,255,255,0.05)' }}>
                  <span className="h-2 w-2 rounded-full" style={{ background: m.color }} /> {m.label} ({n})
                </button>
              );
            })}
          </div>

          {/* Results */}
          <div className="space-y-2">
            {shown.map((g) => {
              const m = TIER_META[g.sizeTier];
              const isAdded = added[g.name] || existingNames.has(g.name.toLowerCase().trim());
              return (
                <div key={g.name} className="rounded-2xl border border-white/5 bg-white/[0.02] p-3.5">
                  <div className="flex items-start gap-3">
                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl" style={{ background: `${m.color}22` }}>
                      <m.icon className="h-5 w-5" style={{ color: m.color }} />
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="truncate text-sm font-semibold text-white">{g.name}</span>
                      </div>
                      <div className="mt-0.5 flex flex-wrap items-center gap-1.5 text-[11px]">
                        <span className="rounded-md px-1.5 py-0.5 font-semibold text-white" style={{ background: `${m.color}cc` }}>
                          {m.label} · {g.estMembers}
                        </span>
                        <span className="text-white/45">{g.niche}</span>
                      </div>
                      {g.relevance && <p className="mt-1.5 text-xs leading-relaxed text-white/55">{g.relevance}</p>}
                      <div className="mt-2.5 flex flex-wrap gap-1.5">
                        <a href={g.searchUrl} target="_blank" rel="noreferrer"
                          className="flex items-center gap-1.5 rounded-lg bg-white/5 px-3 py-1.5 text-xs font-medium text-white/70 transition hover:bg-white/10 hover:text-white">
                          <ExternalLink className="h-3.5 w-3.5" /> View on Facebook
                        </a>
                        <button onClick={() => !isAdded && add(g)} disabled={isAdded || adding}
                          className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition ${
                            isAdded ? 'bg-emerald-500/15 text-emerald-300' : 'bg-[#1877F2] text-white hover:bg-[#0d5fc4]'
                          }`}>
                          {isAdded ? <CheckCircle2 className="h-3.5 w-3.5" /> : <Plus className="h-3.5 w-3.5" />}
                          {isAdded ? 'Added' : 'Add to my groups'}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {result.note && (
            <p className="flex items-start gap-2 rounded-xl border border-white/5 bg-white/[0.02] p-3 text-[11px] text-white/45">
              <ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-300/70" /> {result.note}
            </p>
          )}
        </>
      )}
    </div>
  );
}

// ───────────────────────────── Groups ────────────────────────────────────────
function GroupsTab({ groups, loading, onAdd, adding, onToggle, onDelete }: {
  groups: FbGroup[]; loading: boolean; onAdd: (b: any) => void; adding: boolean;
  onToggle: (id: string, active: boolean) => void; onDelete: (id: string) => void;
}) {
  const [name, setName] = useState('');
  const [url, setUrl] = useState('');
  const [members, setMembers] = useState('');
  const submit = () => {
    if (!name.trim()) return;
    onAdd({ name: name.trim(), url: url.trim() || undefined, memberCount: members ? Number(members) : undefined });
    setName(''); setUrl(''); setMembers('');
  };
  return (
    <div className="space-y-4">
      <div className="rounded-2xl border border-white/5 bg-white/[0.02] p-4">
        <div className="mb-3 text-sm font-semibold text-white">Add open group</div>
        <div className="grid gap-2.5 sm:grid-cols-2">
          <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Group name"
            className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-blue-400/50" />
          <input value={members} onChange={(e) => setMembers(e.target.value.replace(/\D/g, ''))} placeholder="Members (optional)"
            className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-blue-400/50" />
          <input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://facebook.com/groups/..."
            className="sm:col-span-2 rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-blue-400/50" />
        </div>
        <button onClick={submit} disabled={adding || !name.trim()}
          className="mt-3 flex items-center gap-2 rounded-xl bg-[#1877F2] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#0d5fc4] disabled:opacity-40">
          <Plus className="h-4 w-4" /> Add group
        </button>
      </div>

      {loading ? (
        <div className="py-8 text-center text-sm text-white/40">Loading groups…</div>
      ) : groups.length === 0 ? (
        <div className="py-8 text-center text-sm text-white/40">You haven't added any groups yet.</div>
      ) : (
        <div className="space-y-2">
          {groups.map((g) => (
            <div key={g.id} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[0.02] p-3">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg" style={{ background: `${BLUE}22` }}>
                <Facebook className="h-4 w-4" style={{ color: BLUE }} />
              </div>
              <div className="min-w-0 flex-1">
                <div className="truncate text-sm font-medium text-white">{g.name}</div>
                <div className="flex items-center gap-2 text-[11px] text-white/45">
                  {g.memberCount ? <span>{g.memberCount.toLocaleString()} members</span> : null}
                  {g.publishCount ? <span>· {g.publishCount} published</span> : null}
                  {g.url ? (
                    <a href={g.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-0.5 text-blue-300 hover:underline">
                      Open <ExternalLink className="h-3 w-3" />
                    </a>
                  ) : null}
                </div>
              </div>
              <button onClick={() => onToggle(g.id, g.active === false)} title={g.active === false ? 'Activate' : 'Pause'}
                className={`rounded-lg p-2 transition ${g.active === false ? 'text-white/30 hover:text-white/60' : 'text-emerald-300 hover:bg-emerald-500/10'}`}>
                <Power className="h-4 w-4" />
              </button>
              <button onClick={() => onDelete(g.id)} className="rounded-lg p-2 text-white/30 transition hover:bg-red-500/10 hover:text-red-300">
                <Trash2 className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ───────────────────────────── Content ───────────────────────────────────────
function ContentTab({ items, loading, groups, base, onEnqueue, enqueuing }: {
  items: PromotableItem[]; loading: boolean; groups: FbGroup[]; base: string;
  onEnqueue: (b: any) => void; enqueuing: boolean;
}) {
  const [filter, setFilter] = useState<string>('all');
  const [selected, setSelected] = useState<PromotableItem | null>(null);
  const types = useMemo(() => Array.from(new Set(items.map((i) => i.contentType))), [items]);
  const shown = filter === 'all' ? items : items.filter((i) => i.contentType === filter);

  if (loading) return <div className="py-8 text-center text-sm text-white/40">Loading content…</div>;
  if (items.length === 0) return (
    <div className="py-8 text-center text-sm text-white/40">
      No content to promote yet. Publish songs, merch, posts or concerts first.
    </div>
  );

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-1.5">
        <FilterChip active={filter === 'all'} onClick={() => setFilter('all')} label={`All (${items.length})`} />
        {types.map((t) => {
          const meta = TYPE_META[t] || TYPE_META.custom;
          return <FilterChip key={t} active={filter === t} onClick={() => setFilter(t)} label={meta.label} />;
        })}
      </div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        {shown.map((it) => {
          const meta = TYPE_META[it.contentType] || TYPE_META.custom;
          return (
            <button key={`${it.contentType}:${it.contentId}`} onClick={() => setSelected(it)}
              className="group overflow-hidden rounded-2xl border border-white/5 bg-white/[0.02] text-left transition hover:border-blue-400/40">
              <div className="relative aspect-square w-full bg-black/40">
                {it.imageUrl ? (
                  <img src={it.imageUrl} alt="" className="h-full w-full object-cover" />
                ) : (
                  <div className="flex h-full w-full items-center justify-center"><meta.icon className="h-8 w-8" style={{ color: meta.color }} /></div>
                )}
                <span className="absolute left-2 top-2 rounded-md px-1.5 py-0.5 text-[9px] font-semibold uppercase text-white" style={{ background: `${meta.color}cc` }}>{meta.label}</span>
              </div>
              <div className="p-2.5">
                <div className="truncate text-xs font-medium text-white">{it.title}</div>
                {it.subtitle && <div className="truncate text-[10px] text-white/40">{it.subtitle}</div>}
              </div>
            </button>
          );
        })}
      </div>

      <AnimatePresence>
        {selected && (
          <ComposeModal item={selected} groups={groups} base={base} enqueuing={enqueuing}
            onClose={() => setSelected(null)}
            onEnqueue={(b) => { onEnqueue(b); setSelected(null); }} />
        )}
      </AnimatePresence>
    </div>
  );
}

function FilterChip({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) {
  return (
    <button onClick={onClick} className={`rounded-lg px-3 py-1.5 text-xs font-medium transition ${active ? 'bg-blue-500/15 text-blue-200' : 'bg-white/5 text-white/50 hover:text-white'}`}>{label}</button>
  );
}

// ───────────────────── Compose modal (queue an item) ─────────────────────────
function ComposeModal({ item, groups, base, onClose, onEnqueue, enqueuing }: {
  item: PromotableItem; groups: FbGroup[]; base: string;
  onClose: () => void; onEnqueue: (b: any) => void; enqueuing: boolean;
}) {
  const [caption, setCaption] = useState('');
  const [selectedGroups, setSelectedGroups] = useState<string[]>(groups.map((g) => g.id));
  const [generating, setGenerating] = useState(false);
  const meta = TYPE_META[item.contentType] || TYPE_META.custom;

  const generate = async () => {
    setGenerating(true);
    try {
      const res = await apiRequest({
        url: `${base}/generate-caption`, method: 'POST',
        data: { contentType: item.contentType, title: item.title, subtitle: item.subtitle, link: item.link },
      });
      if (res?.caption) setCaption(res.caption);
    } finally { setGenerating(false); }
  };
  const toggle = (id: string) =>
    setSelectedGroups((s) => (s.includes(id) ? s.filter((x) => x !== id) : [...s, id]));

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 z-[120] flex items-center justify-center bg-black/70 p-4" onClick={onClose}>
      <motion.div initial={{ scale: 0.95, y: 10 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, opacity: 0 }}
        onClick={(e) => e.stopPropagation()}
        className="max-h-[88vh] w-full max-w-lg overflow-y-auto rounded-3xl border border-white/10 bg-[#0b1422] p-5">
        <div className="mb-4 flex items-start gap-3">
          {item.imageUrl ? <img src={item.imageUrl} alt="" className="h-14 w-14 shrink-0 rounded-xl object-cover" />
            : <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl" style={{ background: `${meta.color}22` }}><meta.icon className="h-6 w-6" style={{ color: meta.color }} /></div>}
          <div className="min-w-0 flex-1">
            <div className="text-sm font-semibold text-white">{item.title}</div>
            {item.subtitle && <div className="text-xs text-white/45">{item.subtitle}</div>}
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 text-white/40 hover:text-white"><X className="h-5 w-5" /></button>
        </div>

        <div className="mb-3">
          <div className="mb-1.5 flex items-center justify-between">
            <label className="text-xs font-medium text-white/70">Caption</label>
            <button onClick={generate} disabled={generating}
              className="flex items-center gap-1.5 rounded-lg bg-blue-500/15 px-2.5 py-1 text-xs font-medium text-blue-200 disabled:opacity-50">
              {generating ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
              Generate with AI
            </button>
          </div>
          <textarea value={caption} onChange={(e) => setCaption(e.target.value)} rows={4}
            placeholder="Write or generate a caption for the group…"
            className="w-full resize-none rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-blue-400/50" />
        </div>

        <div className="mb-4">
          <div className="mb-1.5 text-xs font-medium text-white/70">Target groups</div>
          {groups.length === 0 ? (
            <div className="text-xs text-white/40">No active groups. Add them in the Groups tab.</div>
          ) : (
            <div className="flex flex-wrap gap-1.5">
              {groups.map((g) => (
                <button key={g.id} onClick={() => toggle(g.id)}
                  className={`rounded-lg px-2.5 py-1.5 text-xs transition ${selectedGroups.includes(g.id) ? 'bg-blue-500/20 text-blue-200 ring-1 ring-blue-400/40' : 'bg-white/5 text-white/50'}`}>
                  {g.name}
                </button>
              ))}
            </div>
          )}
        </div>

        <button
          onClick={() => onEnqueue({
            contentType: item.contentType, contentId: item.contentId, title: item.title,
            subtitle: item.subtitle, imageUrl: item.imageUrl, link: item.link,
            caption: caption.trim() || undefined, groupIds: selectedGroups,
            autoCaption: !caption.trim(),
          })}
          disabled={enqueuing || selectedGroups.length === 0}
          className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#1877F2] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#0d5fc4] disabled:opacity-40">
          <Send className="h-4 w-4" /> Add to queue
        </button>
      </motion.div>
    </motion.div>
  );
}

// ───────────────────────────── Queue ─────────────────────────────────────────
function QueueTab({ items, loading, groups, onPublish, onSkip, onDelete }: {
  items: QueueItem[]; loading: boolean; groups: FbGroup[];
  onPublish: (itemId: string, groupId: string) => void; onSkip: (id: string) => void; onDelete: (id: string) => void;
}) {
  const groupById = useMemo(() => Object.fromEntries(groups.map((g) => [g.id, g])), [groups]);
  const active = items.filter((i) => i.status === 'ready' || i.status === 'scheduled');
  const done = items.filter((i) => i.status === 'published');

  if (loading) return <div className="py-8 text-center text-sm text-white/40">Loading queue…</div>;
  if (items.length === 0) return (
    <div className="py-8 text-center text-sm text-white/40">
      The queue is empty. Use "Prepare queue" or add content from the Content tab.
    </div>
  );

  return (
    <div className="space-y-4">
      {active.map((it) => (
        <QueueCard key={it.id} item={it} groupById={groupById} onPublish={onPublish} onSkip={onSkip} onDelete={onDelete} />
      ))}
      {done.length > 0 && (
        <div className="pt-2">
          <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-white/40">Published ({done.length})</div>
          <div className="space-y-1.5">
            {done.slice(0, 6).map((it) => (
              <div key={it.id} className="flex items-center gap-2 rounded-xl border border-white/5 bg-white/[0.015] px-3 py-2 text-xs text-white/50">
                <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                <span className="truncate">{it.title}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function QueueCard({ item, groupById, onPublish, onSkip, onDelete }: {
  item: QueueItem; groupById: Record<string, FbGroup>;
  onPublish: (itemId: string, groupId: string) => void; onSkip: (id: string) => void; onDelete: (id: string) => void;
}) {
  const [copied, setCopied] = useState(false);
  const meta = TYPE_META[item.contentType] || TYPE_META.custom;
  const published = item.publishedGroups || {};
  const isScheduled = item.status === 'scheduled';

  const copyCaption = async () => {
    const text = item.link ? `${item.caption}\n\n${item.link}` : item.caption;
    try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { /* noop */ }
  };

  // Hybrid 1-click: copy caption → open the group → mark this group published.
  const publishToGroup = async (g: FbGroup) => {
    await copyCaption();
    if (g.url) window.open(g.url, '_blank', 'noopener,noreferrer');
    onPublish(item.id, g.id);
  };

  return (
    <div className="rounded-2xl border border-white/5 bg-white/[0.02] p-4">
      <div className="flex gap-3">
        {item.imageUrl ? (
          <img src={item.imageUrl} alt="" className="h-16 w-16 shrink-0 rounded-xl object-cover" />
        ) : (
          <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-xl" style={{ background: `${meta.color}22` }}>
            <meta.icon className="h-7 w-7" style={{ color: meta.color }} />
          </div>
        )}
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="rounded-md px-1.5 py-0.5 text-[9px] font-semibold uppercase text-white" style={{ background: `${meta.color}cc` }}>{meta.label}</span>
            {isScheduled && (
              <span className="flex items-center gap-1 text-[10px] text-amber-300">
                <Clock className="h-3 w-3" /> {new Date(item.scheduledAt).toLocaleString()}
              </span>
            )}
            {item.autoGenerated && <span className="text-[10px] text-blue-300/70">· auto</span>}
          </div>
          <div className="mt-1 truncate text-sm font-medium text-white">{item.title}</div>
        </div>
        <div className="flex shrink-0 flex-col gap-1">
          <button onClick={() => onSkip(item.id)} title="Skip" className="rounded-lg p-1.5 text-white/30 hover:text-white/60"><SkipForward className="h-4 w-4" /></button>
          <button onClick={() => onDelete(item.id)} title="Delete" className="rounded-lg p-1.5 text-white/30 hover:text-red-300"><Trash2 className="h-4 w-4" /></button>
        </div>
      </div>

      <div className="mt-3 rounded-xl border border-white/5 bg-black/20 p-3">
        <div className="flex items-start justify-between gap-2">
          <p className="whitespace-pre-wrap text-xs leading-relaxed text-white/75">{item.caption}</p>
          <button onClick={copyCaption} className="flex shrink-0 items-center gap-1 rounded-lg bg-white/5 px-2 py-1 text-[10px] text-white/60 hover:text-white">
            {copied ? <CheckCircle2 className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
      </div>

      <div className="mt-3">
        <div className="mb-1.5 text-[11px] font-medium text-white/50">Publish to each group (1 click — copies caption + opens the group):</div>
        <div className="flex flex-wrap gap-1.5">
          {item.groupIds.map((gid) => {
            const g = groupById[gid];
            const isDone = !!published[gid];
            if (!g) return null;
            return (
              <button key={gid} onClick={() => !isDone && publishToGroup(g)} disabled={isDone}
                className={`flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-medium transition ${
                  isDone ? 'bg-emerald-500/15 text-emerald-300' : 'bg-[#1877F2] text-white hover:bg-[#0d5fc4]'
                }`}>
                {isDone ? <CheckCircle2 className="h-3.5 w-3.5" /> : <ExternalLink className="h-3.5 w-3.5" />}
                {g.name}
              </button>
            );
          })}
          {item.groupIds.length === 0 && <span className="text-[11px] text-white/40">No groups assigned.</span>}
        </div>
      </div>
    </div>
  );
}

// ───────────────────────────── Settings ──────────────────────────────────────
function SettingsTab({ settings, groups, onSave, saving }: {
  settings?: FbSettings; groups: FbGroup[]; onSave: (b: any) => void; saving: boolean;
}) {
  const [s, setS] = useState<FbSettings>({
    autopilot: settings?.autopilot ?? false,
    hybridMode: settings?.hybridMode ?? true,
    dailyCap: settings?.dailyCap ?? 8,
    minIntervalMinutes: settings?.minIntervalMinutes ?? 45,
    rotateContent: settings?.rotateContent ?? true,
    tone: settings?.tone ?? 'energetic',
    language: settings?.language ?? 'en',
    defaultGroupIds: settings?.defaultGroupIds ?? [],
  });
  const set = (k: keyof FbSettings, v: any) => setS((p) => ({ ...p, [k]: v }));

  return (
    <div className="space-y-4">
      <ToggleRow label="Autopilot (build the queue automatically)" hint="The engine builds the queue from your content every ~10 min. Still hybrid: you confirm each publish."
        value={s.autopilot} onChange={(v) => set('autopilot', v)} />
      <div className="grid gap-3 sm:grid-cols-2">
        <NumberField label="Daily limit" value={s.dailyCap} min={1} max={50} onChange={(v) => set('dailyCap', v)} />
        <NumberField label="Minimum interval (min)" value={s.minIntervalMinutes} min={5} max={720} onChange={(v) => set('minIntervalMinutes', v)} />
      </div>
      <ToggleRow label="Rotate content types" hint="Alternate songs, merch, concerts… so the queue isn't repetitive."
        value={s.rotateContent} onChange={(v) => set('rotateContent', v)} />
      <div className="grid gap-3 sm:grid-cols-2">
        <SelectField label="Tone" value={s.tone} onChange={(v) => set('tone', v)}
          options={[['energetic', 'Energetic'], ['friendly', 'Friendly'], ['hype', 'Hype'], ['chill', 'Chill'], ['professional', 'Professional']]} />
        <SelectField label="Language" value={s.language} onChange={(v) => set('language', v)}
          options={[['es', 'Spanish'], ['en', 'English']]} />
      </div>

      <div>
        <div className="mb-1.5 text-xs font-medium text-white/70">Default groups (for autopilot)</div>
        {groups.length === 0 ? (
          <div className="text-xs text-white/40">Add groups first.</div>
        ) : (
          <div className="flex flex-wrap gap-1.5">
            {groups.map((g) => (
              <button key={g.id} onClick={() => set('defaultGroupIds', s.defaultGroupIds.includes(g.id) ? s.defaultGroupIds.filter((x) => x !== g.id) : [...s.defaultGroupIds, g.id])}
                className={`rounded-lg px-2.5 py-1.5 text-xs transition ${s.defaultGroupIds.includes(g.id) ? 'bg-blue-500/20 text-blue-200 ring-1 ring-blue-400/40' : 'bg-white/5 text-white/50'}`}>
                {g.name}
              </button>
            ))}
          </div>
        )}
        <p className="mt-1.5 text-[11px] text-white/40">If you don't pick any, autopilot uses all active groups.</p>
      </div>

      <button onClick={() => onSave(s)} disabled={saving}
        className="flex items-center gap-2 rounded-xl bg-[#1877F2] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#0d5fc4] disabled:opacity-40">
        {saving ? <RefreshCw className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />} Save settings
      </button>
    </div>
  );
}

function ToggleRow({ label, hint, value, onChange }: { label: string; hint?: string; value: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-white/[0.02] p-3.5">
      <div className="min-w-0">
        <div className="text-sm text-white">{label}</div>
        {hint && <div className="mt-0.5 text-[11px] text-white/45">{hint}</div>}
      </div>
      <button onClick={() => onChange(!value)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${value ? 'bg-[#1877F2]' : 'bg-white/15'}`}>
        <span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white transition-all ${value ? 'left-[22px]' : 'left-0.5'}`} />
      </button>
    </div>
  );
}
function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (v: number) => void }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-medium text-white/70">{label}</span>
      <input type="number" value={value} min={min} max={max} onChange={(e) => onChange(Math.max(min, Math.min(max, Number(e.target.value) || min)))}
        className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-400/50" />
    </label>
  );
}
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: [string, string][] }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-medium text-white/70">{label}</span>
      <select value={value} onChange={(e) => onChange(e.target.value)}
        className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-400/50">
        {options.map(([v, l]) => <option key={v} value={v} className="bg-[#0b1422]">{l}</option>)}
      </select>
    </label>
  );
}

export default FacebookGroupsCommandCenter;
