import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Layout, ExternalLink, Sparkles, ChevronRight, Copy, Check, Globe } from 'lucide-react';
import { SectionCard } from '../shared/SectionCard';
import { Modal } from '../shared/Modal';
import { TOKENS } from '../shared/tokens';
import { apiRequest } from '../../../lib/queryClient';

interface LandingPage {
  id: number;
  slug: string;
  name: string;
  image: string | null;
  country?: string | null;
  genres: string[];
  pageMode: string;
  isAiGenerated: boolean;
  url: string;
  createdAt: string;
  time: string;
}

interface LandingPagesResponse {
  ok: boolean;
  items: LandingPage[];
  counts?: { total: number; ai: number; last7: number };
}

export function LandingForgeCard() {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);

  const { data, isLoading } = useQuery<LandingPagesResponse>({
    queryKey: ['aas-landing-pages'],
    queryFn: () =>
      apiRequest(
        'GET',
        '/api/admin/artist-acquisition/landing-pages?limit=12'
      ) as any,
    refetchInterval: 60_000,
  });

  const items = data?.items || [];
  const counts = data?.counts;

  const publicUrl = (slug: string) => {
    if (typeof window === 'undefined') return `/artist/${slug}`;
    return `${window.location.origin}/artist/${slug}`;
  };

  const copyUrl = async (slug: string) => {
    try {
      await navigator.clipboard.writeText(publicUrl(slug));
      setCopied(slug);
      setTimeout(() => setCopied(null), 1400);
    } catch {
      /* ignore */
    }
  };

  return (
    <SectionCard
      title="Landing Forge"
      action={
        <div className="flex items-center gap-2">
          {counts && (
            <span
              className="text-[11px] px-2 py-0.5 rounded-full"
              style={{
                color: TOKENS.MUTED,
                background: TOKENS.SURFACE_3,
                border: `1px solid ${TOKENS.BORDER}`,
              }}
              title="Published pages · AI generated · New last 7 days"
            >
              {counts.total} total · {counts.ai} AI · +{counts.last7} / 7d
            </span>
          )}
          <button
            onClick={() => setExpanded(true)}
            className="flex items-center gap-1 text-[11.5px] transition-colors hover:text-white"
            style={{ color: TOKENS.MUTED }}
          >
            View All
            <ChevronRight size={11} />
          </button>
        </div>
      }
      bodyClassName="!py-3"
    >
      <div className="text-[11.5px] mb-3" style={{ color: TOKENS.MUTED }}>
        Live artist landing pages generated by the platform. Every discovered
        artist ships with hero, bio, video and store blocks on a branded{' '}
        <code style={{ color: TOKENS.ORANGE_GLOW }}>/artist/:slug</code> page.
      </div>

      {isLoading && (
        <div className="text-[11.5px]" style={{ color: TOKENS.MUTED }}>
          Loading published pages…
        </div>
      )}

      {!isLoading && items.length === 0 && (
        <div
          className="flex flex-col items-center justify-center py-6 gap-1.5"
          style={{ color: TOKENS.MUTED }}
        >
          <Layout size={20} />
          <div className="text-[11.5px]">
            No artist pages published yet. Run Hunter + Potential Scorer to
            seed discovery.
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        {items.slice(0, 6).map((p) => (
          <LandingRow
            key={p.id}
            page={p}
            copied={copied === p.slug}
            onCopy={() => copyUrl(p.slug)}
          />
        ))}
      </div>

      {/* Full gallery */}
      <Modal
        open={expanded}
        onClose={() => setExpanded(false)}
        title="All artist landing pages"
        subtitle="These are the public /artist/:slug pages served by the platform."
        size="lg"
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          {items.map((p) => (
            <LandingRow
              key={p.id}
              page={p}
              copied={copied === p.slug}
              onCopy={() => copyUrl(p.slug)}
            />
          ))}
        </div>
      </Modal>
    </SectionCard>
  );
}

function LandingRow({
  page,
  copied,
  onCopy,
}: {
  page: LandingPage;
  copied: boolean;
  onCopy: () => void;
}) {
  return (
    <div
      className="flex items-center gap-2.5 p-2 rounded-md transition-colors hover:bg-white/[0.03]"
      style={{ background: TOKENS.SURFACE_3, border: `1px solid ${TOKENS.BORDER}` }}
    >
      <div
        className="w-10 h-10 rounded-md overflow-hidden shrink-0 flex items-center justify-center"
        style={{
          background: TOKENS.ORANGE_SOFT,
          border: `1px solid ${TOKENS.ORANGE_RING}`,
        }}
      >
        {page.image ? (
          <img src={page.image} alt={page.name} className="w-full h-full object-cover" />
        ) : (
          <Layout size={14} style={{ color: TOKENS.ORANGE_GLOW }} />
        )}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5">
          <span
            className="text-[12px] font-semibold truncate"
            style={{ color: TOKENS.TEXT }}
          >
            {page.name}
          </span>
          {page.isAiGenerated && (
            <span
              className="inline-flex items-center gap-0.5 text-[9.5px] px-1.5 rounded-full"
              style={{
                color: TOKENS.ORANGE_GLOW,
                background: TOKENS.ORANGE_SOFT,
                border: `1px solid ${TOKENS.ORANGE_RING}`,
              }}
              title="AI-generated artist"
            >
              <Sparkles size={8} />
              AI
            </span>
          )}
        </div>
        <div
          className="text-[10.5px] truncate flex items-center gap-1"
          style={{ color: TOKENS.MUTED }}
        >
          <Globe size={9} />
          /artist/{page.slug}
          {page.country ? ` • ${page.country}` : ''}
        </div>
      </div>
      <button
        onClick={onCopy}
        className="p-1.5 rounded-md transition-colors hover:bg-white/5"
        style={{ color: copied ? '#7bb77b' : TOKENS.MUTED, border: `1px solid ${TOKENS.BORDER}` }}
        title={copied ? 'Copied!' : 'Copy public URL'}
      >
        {copied ? <Check size={12} /> : <Copy size={12} />}
      </button>
      <a
        href={page.url}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1 px-2 py-1 rounded-md text-[10.5px] font-semibold transition-colors"
        style={{
          color: TOKENS.ORANGE_GLOW,
          background: TOKENS.ORANGE_SOFT,
          border: `1px solid ${TOKENS.ORANGE_RING}`,
        }}
        title="Open live page"
      >
        Open
        <ExternalLink size={10} />
      </a>
    </div>
  );
}
